/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.commonsenseneo.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.commonsenseneo.block.*;
import net.mcreator.commonsenseneo.CommonSenseMod;

public class CommonSenseModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(CommonSenseMod.MODID);
	public static final DeferredBlock<Block> AMBER_ORE;
	public static final DeferredBlock<Block> DEEP_SLATE_AMBER_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_AMBER;
	public static final DeferredBlock<Block> END_FRAGMENT_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_ANCIENT_ORE;
	public static final DeferredBlock<Block> NETHERACK_IRON_ORE;
	public static final DeferredBlock<Block> NITER_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_NITER;
	public static final DeferredBlock<Block> SULFUR_ORE;
	public static final DeferredBlock<Block> BLOCK_OF_SULFUR;
	public static final DeferredBlock<Block> STONE_DOOR;
	public static final DeferredBlock<Block> QUICK_STEP;
	public static final DeferredBlock<Block> COMPRESSED_IRON_BLOCK;
	public static final DeferredBlock<Block> COMPRESSED_GOLD_BLOCK;
	public static final DeferredBlock<Block> COMPRESSED_DIAMOND_BLOCK;
	public static final DeferredBlock<Block> COMPRESSED_EMERALD_BLOCK;
	public static final DeferredBlock<Block> COMPRESSED_NETHERITE_BLOCK;
	public static final DeferredBlock<Block> COMPRESSED_COBBLE_STONE;
	public static final DeferredBlock<Block> DOUBLE_COMPRESSED_COBBLE_STONE;
	public static final DeferredBlock<Block> TRIPLE_COMPRESSED_COBBLE_STONE;
	public static final DeferredBlock<Block> QUADRUPLE_COMPRESSED_COBBLE_STONE;
	public static final DeferredBlock<Block> COMPRESSED_NETHERACK;
	public static final DeferredBlock<Block> COMPRESSED_ENDSTONE;
	public static final DeferredBlock<Block> COMPRESSED_OBSIDAN;
	public static final DeferredBlock<Block> DOUBLE_COMPRESSED_OBSIDAN;
	public static final DeferredBlock<Block> TRIPLE_COMPRESSED_OBSIDAN;
	public static final DeferredBlock<Block> COMPRESSED_COAL_BLOCK;
	public static final DeferredBlock<Block> DOUBLE_COMPRESSED_COAL_BLOCK;
	public static final DeferredBlock<Block> INRICHED_COAL_BLOCK;
	public static final DeferredBlock<Block> COMPRESSED_TNT;
	public static final DeferredBlock<Block> DEEPSLATE_NITER_ORE;
	public static final DeferredBlock<Block> DEEP_SLATE_SULFUR_ORE;
	public static final DeferredBlock<Block> ANDESITE_IRON_ORE;
	public static final DeferredBlock<Block> ANDESITE_DIAMOND_ORE;
	public static final DeferredBlock<Block> ANDESITE_GOLD_ORE;
	public static final DeferredBlock<Block> ANDESITE_LAPIS_ORE;
	public static final DeferredBlock<Block> ANDESITE_EMERALD_ORE;
	public static final DeferredBlock<Block> ANDESITE_REDSTONE_ORE;
	public static final DeferredBlock<Block> ANDESITE_COAL_ORE;
	public static final DeferredBlock<Block> ANDESITE_COPPER_ORE;
	public static final DeferredBlock<Block> DIORITE_IRON_ORE;
	public static final DeferredBlock<Block> DIORITE_COPPER_ORE;
	public static final DeferredBlock<Block> DIORITE_GOLD_ORE;
	public static final DeferredBlock<Block> DIORITE_DIAMOND_ORE;
	public static final DeferredBlock<Block> DIORITE_EMERALD_ORE;
	public static final DeferredBlock<Block> DIORITE_LAPIS_ORE;
	public static final DeferredBlock<Block> DIORITE_REDSTONE_ORE;
	public static final DeferredBlock<Block> DIORITE_COAL_ORE;
	public static final DeferredBlock<Block> GRANITE_IRON_ORE;
	public static final DeferredBlock<Block> GRANITE_GOLD_ORE;
	public static final DeferredBlock<Block> GRANITE_COPPER_ORE;
	public static final DeferredBlock<Block> GRANITE_DIAMOND_ORE;
	public static final DeferredBlock<Block> GRANITE_EMERALD_ORE;
	public static final DeferredBlock<Block> GRANITE_REDSTONE_ORE;
	public static final DeferredBlock<Block> GRANITE_COAL_ORE;
	public static final DeferredBlock<Block> GRANITE_LAPIS_ORE;
	public static final DeferredBlock<Block> SNOW_DIRT;
	public static final DeferredBlock<Block> CHAIN_FENCE;
	public static final DeferredBlock<Block> OAK_BARK_BLOCK;
	public static final DeferredBlock<Block> BIRCH_BARK_BLOCK;
	public static final DeferredBlock<Block> ACACIA_BARK_BLOCK;
	public static final DeferredBlock<Block> SPRUCE_BARK_BLOCK;
	public static final DeferredBlock<Block> CHERRY_BARK_BLOCK;
	public static final DeferredBlock<Block> DARK_OAK_BARK_BLOCK;
	public static final DeferredBlock<Block> JUNGLE_BARK_BLOCK;
	public static final DeferredBlock<Block> MANGROVE_BARK_BLOCK;
	public static final DeferredBlock<Block> HOLLOW_STONE_BRICK;
	public static final DeferredBlock<Block> HOLLOW_STONE_BRICK_LADDER;
	public static final DeferredBlock<Block> LIGHT_BULB_BLOCK;
	public static final DeferredBlock<Block> LIGHT_BULB_BLOCK_ON;
	public static final DeferredBlock<Block> OBSIDIAN_STAIRS;
	public static final DeferredBlock<Block> OBSIDIAN_SLAB;
	public static final DeferredBlock<Block> OBSIDIAN_PRESSURE_PLATE;
	public static final DeferredBlock<Block> OBSIDIAN_WALL;
	public static final DeferredBlock<Block> OBSIDIAN_BUTTON;
	public static final DeferredBlock<Block> OBSIDIAN_BRICK;
	public static final DeferredBlock<Block> OBSIDIAN_BRICK_STAIRS;
	public static final DeferredBlock<Block> OBSIDIAN_BRICK_SLAB;
	public static final DeferredBlock<Block> MARBLE_BLOCK;
	public static final DeferredBlock<Block> MARBLE_STAIRS;
	public static final DeferredBlock<Block> MARBLE_SLAB;
	public static final DeferredBlock<Block> MARBLE_WALL;
	public static final DeferredBlock<Block> MARBLE_PRESSURE_PLATE;
	public static final DeferredBlock<Block> MARBLE_BUTTON;
	public static final DeferredBlock<Block> OAK_LEAVES_WALL;
	public static final DeferredBlock<Block> CHERRY_LEAVES_WALL;
	public static final DeferredBlock<Block> MANGROVE_LEAVES_WALL;
	public static final DeferredBlock<Block> JUNGLE_LEAVES_WALL;
	public static final DeferredBlock<Block> BIRCH_LEAVES_WALL;
	public static final DeferredBlock<Block> ACACIA_LEAVES_WALL;
	public static final DeferredBlock<Block> DARK_OAK_LEAVES_WALL;
	public static final DeferredBlock<Block> SPRUCE_LEAVES_WALL;
	public static final DeferredBlock<Block> AZALEA_LEAVES_WALL;
	public static final DeferredBlock<Block> BURNT_LOG;
	public static final DeferredBlock<Block> STRIPPED_BURNT_LOG;
	public static final DeferredBlock<Block> OAK_STAIRS;
	public static final DeferredBlock<Block> OAK_SLAB;
	public static final DeferredBlock<Block> IRON_BARS_GATE;
	public static final DeferredBlock<Block> IRON_BARS_GATE_OPEN;
	public static final DeferredBlock<Block> SPONGE_STEM;
	public static final DeferredBlock<Block> STEEL_BLOCK;
	public static final DeferredBlock<Block> ANCIENT_ORE;
	public static final DeferredBlock<Block> A_CLUFF_OF_CLOVERS;
	public static final DeferredBlock<Block> A_CLUFF_OF_MORE_CLOVERS;
	public static final DeferredBlock<Block> A_CLUFF_OF_EVEN_MORE_CLOVERS;
	public static final DeferredBlock<Block> A_CLUFF_OF_SO_MUCH_CLOVERS;
	public static final DeferredBlock<Block> CLOVER_IN_A_POT;
	public static final DeferredBlock<Block> VERTICAL_CHAIN;
	public static final DeferredBlock<Block> IRON_TOWER;
	public static final DeferredBlock<Block> IRON_TOWER_TOP;
	public static final DeferredBlock<Block> ENDSTONE_NETHERITE_ORE;
	public static final DeferredBlock<Block> BERYLLIUM_ORE;
	public static final DeferredBlock<Block> WHITE_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> ORANGE_CONCRETE_STAIR;
	public static final DeferredBlock<Block> LIGHT_GRAY_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> MAGENTA_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> LIGHT_BLUE_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> YELLOW_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> LIME_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> PINK_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> GRAY_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> CYAN_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> PURPLE_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> BLUE_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> BROWN_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> GREEN_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> RED_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> BLACK_CONCRETE_STAIRS;
	public static final DeferredBlock<Block> IRON_TOWER_POWERED;
	public static final DeferredBlock<Block> IRON_TOWER_TOP_POWERED;
	public static final DeferredBlock<Block> RUBY_ORE;
	public static final DeferredBlock<Block> RUBY_BLOCK;
	public static final DeferredBlock<Block> OLD_STONECUTTER;
	public static final DeferredBlock<Block> WHITE_CONCRETE_SLAB;
	public static final DeferredBlock<Block> ORANGE_CONCRETE_SLAB;
	public static final DeferredBlock<Block> LIGHT_GRAY_CONCRETE_SLAB;
	public static final DeferredBlock<Block> GRAY_CONCRETE_SLAB;
	public static final DeferredBlock<Block> BLACK_CONCRETE_SLAB;
	public static final DeferredBlock<Block> MAGENTA_CONCRETE_SLAB;
	public static final DeferredBlock<Block> LIGHT_BLUE_CONCRETE_SLAB;
	public static final DeferredBlock<Block> YELLOW_CONCRETE_SLAB;
	public static final DeferredBlock<Block> LIME_CONCRETE_SLAB;
	public static final DeferredBlock<Block> PINK_CONCRETE_SLAB;
	public static final DeferredBlock<Block> CYAN_CONCRETE_SLAB;
	public static final DeferredBlock<Block> PURPLE_CONCRETE_SLAB;
	public static final DeferredBlock<Block> BLUE_CONCRETE_SLAB;
	public static final DeferredBlock<Block> BROWN_CONCRETE_SLAB;
	public static final DeferredBlock<Block> GREEN_CONCRETE_SLAB;
	public static final DeferredBlock<Block> RED_CONCRETE_SLAB;
	public static final DeferredBlock<Block> GLASS_FRAME;
	public static final DeferredBlock<Block> BLOCK_OF_FERTILIZER;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_14;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_13;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_12;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_11;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_10;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_9;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_8;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_7;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_6;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_5;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_4;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_3;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_2;
	public static final DeferredBlock<Block> DIRT_PATH_LAYER_1;
	static {
		AMBER_ORE = REGISTRY.register("amber_ore", AmberOreBlock::new);
		DEEP_SLATE_AMBER_ORE = REGISTRY.register("deep_slate_amber_ore", DeepSlateAmberOreBlock::new);
		BLOCK_OF_AMBER = REGISTRY.register("block_of_amber", BlockOfAmberBlock::new);
		END_FRAGMENT_ORE = REGISTRY.register("end_fragment_ore", EndFragmentOreBlock::new);
		BLOCK_OF_ANCIENT_ORE = REGISTRY.register("block_of_ancient_ore", BlockOfAncientOreBlock::new);
		NETHERACK_IRON_ORE = REGISTRY.register("netherack_iron_ore", NetherackIronOreBlock::new);
		NITER_ORE = REGISTRY.register("niter_ore", NiterOreBlock::new);
		BLOCK_OF_NITER = REGISTRY.register("block_of_niter", BlockOfNiterBlock::new);
		SULFUR_ORE = REGISTRY.register("sulfur_ore", SulfurOreBlock::new);
		BLOCK_OF_SULFUR = REGISTRY.register("block_of_sulfur", BlockOfSulfurBlock::new);
		STONE_DOOR = REGISTRY.register("stone_door", StoneDoorBlock::new);
		QUICK_STEP = REGISTRY.register("quick_step", QuickStepBlock::new);
		COMPRESSED_IRON_BLOCK = REGISTRY.register("compressed_iron_block", CompressedIronBlockBlock::new);
		COMPRESSED_GOLD_BLOCK = REGISTRY.register("compressed_gold_block", CompressedGoldBlockBlock::new);
		COMPRESSED_DIAMOND_BLOCK = REGISTRY.register("compressed_diamond_block", CompressedDiamondBlockBlock::new);
		COMPRESSED_EMERALD_BLOCK = REGISTRY.register("compressed_emerald_block", CompressedEmeraldBlockBlock::new);
		COMPRESSED_NETHERITE_BLOCK = REGISTRY.register("compressed_netherite_block", CompressedNetheriteBlockBlock::new);
		COMPRESSED_COBBLE_STONE = REGISTRY.register("compressed_cobble_stone", CompressedCobbleStoneBlock::new);
		DOUBLE_COMPRESSED_COBBLE_STONE = REGISTRY.register("double_compressed_cobble_stone", DoubleCompressedCobbleStoneBlock::new);
		TRIPLE_COMPRESSED_COBBLE_STONE = REGISTRY.register("triple_compressed_cobble_stone", TripleCompressedCobbleStoneBlock::new);
		QUADRUPLE_COMPRESSED_COBBLE_STONE = REGISTRY.register("quadruple_compressed_cobble_stone", QuadrupleCompressedCobbleStoneBlock::new);
		COMPRESSED_NETHERACK = REGISTRY.register("compressed_netherack", CompressedNetherackBlock::new);
		COMPRESSED_ENDSTONE = REGISTRY.register("compressed_endstone", CompressedEndstoneBlock::new);
		COMPRESSED_OBSIDAN = REGISTRY.register("compressed_obsidan", CompressedObsidanBlock::new);
		DOUBLE_COMPRESSED_OBSIDAN = REGISTRY.register("double_compressed_obsidan", DoubleCompressedObsidanBlock::new);
		TRIPLE_COMPRESSED_OBSIDAN = REGISTRY.register("triple_compressed_obsidan", TripleCompressedObsidanBlock::new);
		COMPRESSED_COAL_BLOCK = REGISTRY.register("compressed_coal_block", CompressedCoalBlockBlock::new);
		DOUBLE_COMPRESSED_COAL_BLOCK = REGISTRY.register("double_compressed_coal_block", DoubleCompressedCoalBlockBlock::new);
		INRICHED_COAL_BLOCK = REGISTRY.register("inriched_coal_block", InrichedCoalBlockBlock::new);
		COMPRESSED_TNT = REGISTRY.register("compressed_tnt", CompressedTNTBlock::new);
		DEEPSLATE_NITER_ORE = REGISTRY.register("deepslate_niter_ore", DeepslateNiterOreBlock::new);
		DEEP_SLATE_SULFUR_ORE = REGISTRY.register("deep_slate_sulfur_ore", DeepSlateSulfurOreBlock::new);
		ANDESITE_IRON_ORE = REGISTRY.register("andesite_iron_ore", AndesiteIronOreBlock::new);
		ANDESITE_DIAMOND_ORE = REGISTRY.register("andesite_diamond_ore", AndesiteDiamondOreBlock::new);
		ANDESITE_GOLD_ORE = REGISTRY.register("andesite_gold_ore", AndesiteGoldOreBlock::new);
		ANDESITE_LAPIS_ORE = REGISTRY.register("andesite_lapis_ore", AndesiteLapisOreBlock::new);
		ANDESITE_EMERALD_ORE = REGISTRY.register("andesite_emerald_ore", AndesiteEmeraldOreBlock::new);
		ANDESITE_REDSTONE_ORE = REGISTRY.register("andesite_redstone_ore", AndesiteRedstoneOreBlock::new);
		ANDESITE_COAL_ORE = REGISTRY.register("andesite_coal_ore", AndesiteCoalOreBlock::new);
		ANDESITE_COPPER_ORE = REGISTRY.register("andesite_copper_ore", AndesiteCopperOreBlock::new);
		DIORITE_IRON_ORE = REGISTRY.register("diorite_iron_ore", DioriteIronOreBlock::new);
		DIORITE_COPPER_ORE = REGISTRY.register("diorite_copper_ore", DioriteCopperOreBlock::new);
		DIORITE_GOLD_ORE = REGISTRY.register("diorite_gold_ore", DioriteGoldOreBlock::new);
		DIORITE_DIAMOND_ORE = REGISTRY.register("diorite_diamond_ore", DioriteDiamondOreBlock::new);
		DIORITE_EMERALD_ORE = REGISTRY.register("diorite_emerald_ore", DioriteEmeraldOreBlock::new);
		DIORITE_LAPIS_ORE = REGISTRY.register("diorite_lapis_ore", DioriteLapisOreBlock::new);
		DIORITE_REDSTONE_ORE = REGISTRY.register("diorite_redstone_ore", DioriteRedstoneOreBlock::new);
		DIORITE_COAL_ORE = REGISTRY.register("diorite_coal_ore", DioriteCoalOreBlock::new);
		GRANITE_IRON_ORE = REGISTRY.register("granite_iron_ore", GraniteIronOreBlock::new);
		GRANITE_GOLD_ORE = REGISTRY.register("granite_gold_ore", GraniteGoldOreBlock::new);
		GRANITE_COPPER_ORE = REGISTRY.register("granite_copper_ore", GraniteCopperOreBlock::new);
		GRANITE_DIAMOND_ORE = REGISTRY.register("granite_diamond_ore", GraniteDiamondOreBlock::new);
		GRANITE_EMERALD_ORE = REGISTRY.register("granite_emerald_ore", GraniteEmeraldOreBlock::new);
		GRANITE_REDSTONE_ORE = REGISTRY.register("granite_redstone_ore", GraniteRedstoneOreBlock::new);
		GRANITE_COAL_ORE = REGISTRY.register("granite_coal_ore", GraniteCoalOreBlock::new);
		GRANITE_LAPIS_ORE = REGISTRY.register("granite_lapis_ore", GraniteLapisOreBlock::new);
		SNOW_DIRT = REGISTRY.register("snow_dirt", SnowDirtBlock::new);
		CHAIN_FENCE = REGISTRY.register("chain_fence", ChainFenceBlock::new);
		OAK_BARK_BLOCK = REGISTRY.register("oak_bark_block", OakBarkBlockBlock::new);
		BIRCH_BARK_BLOCK = REGISTRY.register("birch_bark_block", BirchBarkBlockBlock::new);
		ACACIA_BARK_BLOCK = REGISTRY.register("acacia_bark_block", AcaciaBarkBlockBlock::new);
		SPRUCE_BARK_BLOCK = REGISTRY.register("spruce_bark_block", SpruceBarkBlockBlock::new);
		CHERRY_BARK_BLOCK = REGISTRY.register("cherry_bark_block", CherryBarkBlockBlock::new);
		DARK_OAK_BARK_BLOCK = REGISTRY.register("dark_oak_bark_block", DarkOakBarkBlockBlock::new);
		JUNGLE_BARK_BLOCK = REGISTRY.register("jungle_bark_block", JungleBarkBlockBlock::new);
		MANGROVE_BARK_BLOCK = REGISTRY.register("mangrove_bark_block", MangroveBarkBlockBlock::new);
		HOLLOW_STONE_BRICK = REGISTRY.register("hollow_stone_brick", HollowStoneBrickBlock::new);
		HOLLOW_STONE_BRICK_LADDER = REGISTRY.register("hollow_stone_brick_ladder", HollowStoneBrickLadderBlock::new);
		LIGHT_BULB_BLOCK = REGISTRY.register("light_bulb_block", LightBulbBlockBlock::new);
		LIGHT_BULB_BLOCK_ON = REGISTRY.register("light_bulb_block_on", LightBulbBlockOnBlock::new);
		OBSIDIAN_STAIRS = REGISTRY.register("obsidian_stairs", ObsidianStairsBlock::new);
		OBSIDIAN_SLAB = REGISTRY.register("obsidian_slab", ObsidianSlabBlock::new);
		OBSIDIAN_PRESSURE_PLATE = REGISTRY.register("obsidian_pressure_plate", ObsidianPressurePlateBlock::new);
		OBSIDIAN_WALL = REGISTRY.register("obsidian_wall", ObsidianWallBlock::new);
		OBSIDIAN_BUTTON = REGISTRY.register("obsidian_button", ObsidianButtonBlock::new);
		OBSIDIAN_BRICK = REGISTRY.register("obsidian_brick", ObsidianBrickBlock::new);
		OBSIDIAN_BRICK_STAIRS = REGISTRY.register("obsidian_brick_stairs", ObsidianBrickStairsBlock::new);
		OBSIDIAN_BRICK_SLAB = REGISTRY.register("obsidian_brick_slab", ObsidianBrickSlabBlock::new);
		MARBLE_BLOCK = REGISTRY.register("marble_block", MarbleBlockBlock::new);
		MARBLE_STAIRS = REGISTRY.register("marble_stairs", MarbleStairsBlock::new);
		MARBLE_SLAB = REGISTRY.register("marble_slab", MarbleSlabBlock::new);
		MARBLE_WALL = REGISTRY.register("marble_wall", MarbleWallBlock::new);
		MARBLE_PRESSURE_PLATE = REGISTRY.register("marble_pressure_plate", MarblePressurePlateBlock::new);
		MARBLE_BUTTON = REGISTRY.register("marble_button", MarbleButtonBlock::new);
		OAK_LEAVES_WALL = REGISTRY.register("oak_leaves_wall", OakLeavesWallBlock::new);
		CHERRY_LEAVES_WALL = REGISTRY.register("cherry_leaves_wall", CherryLeavesWallBlock::new);
		MANGROVE_LEAVES_WALL = REGISTRY.register("mangrove_leaves_wall", MangroveLeavesWallBlock::new);
		JUNGLE_LEAVES_WALL = REGISTRY.register("jungle_leaves_wall", JungleLeavesWallBlock::new);
		BIRCH_LEAVES_WALL = REGISTRY.register("birch_leaves_wall", BirchLeavesWallBlock::new);
		ACACIA_LEAVES_WALL = REGISTRY.register("acacia_leaves_wall", AcaciaLeavesWallBlock::new);
		DARK_OAK_LEAVES_WALL = REGISTRY.register("dark_oak_leaves_wall", DarkOakLeavesWallBlock::new);
		SPRUCE_LEAVES_WALL = REGISTRY.register("spruce_leaves_wall", SpruceLeavesWallBlock::new);
		AZALEA_LEAVES_WALL = REGISTRY.register("azalea_leaves_wall", AzaleaLeavesWallBlock::new);
		BURNT_LOG = REGISTRY.register("burnt_log", BurntLogBlock::new);
		STRIPPED_BURNT_LOG = REGISTRY.register("stripped_burnt_log", StrippedBurntLogBlock::new);
		OAK_STAIRS = REGISTRY.register("oak_stairs", OakStairsBlock::new);
		OAK_SLAB = REGISTRY.register("oak_slab", OakSlabBlock::new);
		IRON_BARS_GATE = REGISTRY.register("iron_bars_gate", IronBarsGateBlock::new);
		IRON_BARS_GATE_OPEN = REGISTRY.register("iron_bars_gate_open", IronBarsGateOpenBlock::new);
		SPONGE_STEM = REGISTRY.register("sponge_stem", SpongeStemBlock::new);
		STEEL_BLOCK = REGISTRY.register("steel_block", SteelBlockBlock::new);
		ANCIENT_ORE = REGISTRY.register("ancient_ore", AncientOreBlock::new);
		A_CLUFF_OF_CLOVERS = REGISTRY.register("a_cluff_of_clovers", ACluffOfCloversBlock::new);
		A_CLUFF_OF_MORE_CLOVERS = REGISTRY.register("a_cluff_of_more_clovers", ACluffOfMoreCloversBlock::new);
		A_CLUFF_OF_EVEN_MORE_CLOVERS = REGISTRY.register("a_cluff_of_even_more_clovers", ACluffOfEvenMoreCloversBlock::new);
		A_CLUFF_OF_SO_MUCH_CLOVERS = REGISTRY.register("a_cluff_of_so_much_clovers", ACluffOfSoMuchCloversBlock::new);
		CLOVER_IN_A_POT = REGISTRY.register("clover_in_a_pot", CloverInAPotBlock::new);
		VERTICAL_CHAIN = REGISTRY.register("vertical_chain", VerticalChainBlock::new);
		IRON_TOWER = REGISTRY.register("iron_tower", IronTowerBlock::new);
		IRON_TOWER_TOP = REGISTRY.register("iron_tower_top", IronTowerTopBlock::new);
		ENDSTONE_NETHERITE_ORE = REGISTRY.register("endstone_netherite_ore", EndstoneNetheriteOreBlock::new);
		BERYLLIUM_ORE = REGISTRY.register("beryllium_ore", BerylliumOreBlock::new);
		WHITE_CONCRETE_STAIRS = REGISTRY.register("white_concrete_stairs", WhiteConcreteStairsBlock::new);
		ORANGE_CONCRETE_STAIR = REGISTRY.register("orange_concrete_stair", OrangeConcreteStairBlock::new);
		LIGHT_GRAY_CONCRETE_STAIRS = REGISTRY.register("light_gray_concrete_stairs", LightGrayConcreteStairsBlock::new);
		MAGENTA_CONCRETE_STAIRS = REGISTRY.register("magenta_concrete_stairs", MagentaConcreteStairsBlock::new);
		LIGHT_BLUE_CONCRETE_STAIRS = REGISTRY.register("light_blue_concrete_stairs", LightBlueConcreteStairsBlock::new);
		YELLOW_CONCRETE_STAIRS = REGISTRY.register("yellow_concrete_stairs", YellowConcreteStairsBlock::new);
		LIME_CONCRETE_STAIRS = REGISTRY.register("lime_concrete_stairs", LimeConcreteStairsBlock::new);
		PINK_CONCRETE_STAIRS = REGISTRY.register("pink_concrete_stairs", PinkConcreteStairsBlock::new);
		GRAY_CONCRETE_STAIRS = REGISTRY.register("gray_concrete_stairs", GrayConcreteStairsBlock::new);
		CYAN_CONCRETE_STAIRS = REGISTRY.register("cyan_concrete_stairs", CyanConcreteStairsBlock::new);
		PURPLE_CONCRETE_STAIRS = REGISTRY.register("purple_concrete_stairs", PurpleConcreteStairsBlock::new);
		BLUE_CONCRETE_STAIRS = REGISTRY.register("blue_concrete_stairs", BlueConcreteStairsBlock::new);
		BROWN_CONCRETE_STAIRS = REGISTRY.register("brown_concrete_stairs", BrownConcreteStairsBlock::new);
		GREEN_CONCRETE_STAIRS = REGISTRY.register("green_concrete_stairs", GreenConcreteStairsBlock::new);
		RED_CONCRETE_STAIRS = REGISTRY.register("red_concrete_stairs", RedConcreteStairsBlock::new);
		BLACK_CONCRETE_STAIRS = REGISTRY.register("black_concrete_stairs", BlackConcreteStairsBlock::new);
		IRON_TOWER_POWERED = REGISTRY.register("iron_tower_powered", IronTowerPoweredBlock::new);
		IRON_TOWER_TOP_POWERED = REGISTRY.register("iron_tower_top_powered", IronTowerTopPoweredBlock::new);
		RUBY_ORE = REGISTRY.register("ruby_ore", RubyOreBlock::new);
		RUBY_BLOCK = REGISTRY.register("ruby_block", RubyBlockBlock::new);
		OLD_STONECUTTER = REGISTRY.register("old_stonecutter", OldStonecutterBlock::new);
		WHITE_CONCRETE_SLAB = REGISTRY.register("white_concrete_slab", WhiteConcreteSlabBlock::new);
		ORANGE_CONCRETE_SLAB = REGISTRY.register("orange_concrete_slab", OrangeConcreteSlabBlock::new);
		LIGHT_GRAY_CONCRETE_SLAB = REGISTRY.register("light_gray_concrete_slab", LightGrayConcreteSlabBlock::new);
		GRAY_CONCRETE_SLAB = REGISTRY.register("gray_concrete_slab", GrayConcreteSlabBlock::new);
		BLACK_CONCRETE_SLAB = REGISTRY.register("black_concrete_slab", BlackConcreteSlabBlock::new);
		MAGENTA_CONCRETE_SLAB = REGISTRY.register("magenta_concrete_slab", MagentaConcreteSlabBlock::new);
		LIGHT_BLUE_CONCRETE_SLAB = REGISTRY.register("light_blue_concrete_slab", LightBlueConcreteSlabBlock::new);
		YELLOW_CONCRETE_SLAB = REGISTRY.register("yellow_concrete_slab", YellowConcreteSlabBlock::new);
		LIME_CONCRETE_SLAB = REGISTRY.register("lime_concrete_slab", LimeConcreteSlabBlock::new);
		PINK_CONCRETE_SLAB = REGISTRY.register("pink_concrete_slab", PinkConcreteSlabBlock::new);
		CYAN_CONCRETE_SLAB = REGISTRY.register("cyan_concrete_slab", CyanConcreteSlabBlock::new);
		PURPLE_CONCRETE_SLAB = REGISTRY.register("purple_concrete_slab", PurpleConcreteSlabBlock::new);
		BLUE_CONCRETE_SLAB = REGISTRY.register("blue_concrete_slab", BlueConcreteSlabBlock::new);
		BROWN_CONCRETE_SLAB = REGISTRY.register("brown_concrete_slab", BrownConcreteSlabBlock::new);
		GREEN_CONCRETE_SLAB = REGISTRY.register("green_concrete_slab", GreenConcreteSlabBlock::new);
		RED_CONCRETE_SLAB = REGISTRY.register("red_concrete_slab", RedConcreteSlabBlock::new);
		GLASS_FRAME = REGISTRY.register("glass_frame", GlassFrameBlock::new);
		BLOCK_OF_FERTILIZER = REGISTRY.register("block_of_fertilizer", BlockOfFertilizerBlock::new);
		DIRT_PATH_LAYER_14 = REGISTRY.register("dirt_path_layer_14", DirtPathLayer14Block::new);
		DIRT_PATH_LAYER_13 = REGISTRY.register("dirt_path_layer_13", DirtPathLayer13Block::new);
		DIRT_PATH_LAYER_12 = REGISTRY.register("dirt_path_layer_12", DirtPathLayer12Block::new);
		DIRT_PATH_LAYER_11 = REGISTRY.register("dirt_path_layer_11", DirtPathLayer11Block::new);
		DIRT_PATH_LAYER_10 = REGISTRY.register("dirt_path_layer_10", DirtPathLayer10Block::new);
		DIRT_PATH_LAYER_9 = REGISTRY.register("dirt_path_layer_9", DirtPathLayer9Block::new);
		DIRT_PATH_LAYER_8 = REGISTRY.register("dirt_path_layer_8", DirtPathLayer8Block::new);
		DIRT_PATH_LAYER_7 = REGISTRY.register("dirt_path_layer_7", DirtPathLayer7Block::new);
		DIRT_PATH_LAYER_6 = REGISTRY.register("dirt_path_layer_6", DirtPathLayer6Block::new);
		DIRT_PATH_LAYER_5 = REGISTRY.register("dirt_path_layer_5", DirtPathLayer5Block::new);
		DIRT_PATH_LAYER_4 = REGISTRY.register("dirt_path_layer_4", DirtPathLayer4Block::new);
		DIRT_PATH_LAYER_3 = REGISTRY.register("dirt_path_layer_3", DirtPathLayer3Block::new);
		DIRT_PATH_LAYER_2 = REGISTRY.register("dirt_path_layer_2", DirtPathLayer2Block::new);
		DIRT_PATH_LAYER_1 = REGISTRY.register("dirt_path_layer_1", DirtPathLayer1Block::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}