package net.mcreator.commonsenseneo.init;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.alchemy.Potions;
import net.minecraft.world.item.alchemy.PotionContents;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.component.DataComponents;

import mezz.jei.api.registration.IRecipeRegistration;
import mezz.jei.api.recipe.vanilla.IVanillaRecipeFactory;
import mezz.jei.api.recipe.vanilla.IJeiBrewingRecipe;
import mezz.jei.api.constants.RecipeTypes;
import mezz.jei.api.JeiPlugin;
import mezz.jei.api.IModPlugin;

import java.util.List;
import java.util.ArrayList;

@JeiPlugin
public class CommonSenseModBrewingRecipes implements IModPlugin {
	@Override
	public ResourceLocation getPluginUid() {
		return ResourceLocation.parse("common_sense:brewing_recipes");
	}

	@Override
	public void registerRecipes(IRecipeRegistration registration) {
		IVanillaRecipeFactory factory = registration.getVanillaRecipeFactory();
		List<IJeiBrewingRecipe> brewingRecipes = new ArrayList<>();
		ItemStack potion = new ItemStack(Items.POTION);
		ItemStack potion2 = new ItemStack(Items.POTION);
		List<ItemStack> ingredientStack = new ArrayList<>();
		List<ItemStack> inputStack = new ArrayList<>();
		ingredientStack.add(new ItemStack(CommonSenseModItems.CLOVER_LEAF.get()));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LUCK));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Blocks.FERN));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.POTION_OF_UNLUCK));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LONG_FIRE_RESISTANCE));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FIRE_RESISTANCE_EXTENDED_II));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_HARMING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HARMING_III));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HARMING_III));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HARMING_IV));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HARMING_IV));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HARMING_V));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FIRE_RESISTANCE_EXTENDED_II));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FIRE_RESISTANCE_EXTENDED_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FIRE_RESISTANCE_EXTENDED_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FIRE_RESISTANCE_EXTENDED_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_HEALING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HEALING_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HEALING_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HEALING_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HEALING_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HEALING_5));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LONG_INVISIBILITY));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.INVISIBILITY_EXTENDED_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.INVISIBILITY_EXTENDED_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.INVISIBILITY_EXTENDED_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.INVISIBILITY_EXTENDED_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.INVISIBILITY_EXTENDED_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Blocks.REDSTONE_BLOCK));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.INVISIBILITY_EXTENDED_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.INVISIBILITY_EXTENDED_5));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_LEAPING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_2_EXTENDED_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_2_EXTENDED_1));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_2_EXTENDED_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_LEAPING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_3_EXTENDED_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_4_EXTENDED_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEAPING_5));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(CommonSenseModItems.GOLD_CHOCOLATE_BAR.get()));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.THICK));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_2_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.ABSORPTION_5));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LONG_NIGHT_VISION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.NIGHT_VISION_EX_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.NIGHT_VISION_EX_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.NIGHT_VISION_EX_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.NIGHT_VISION_EX_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.NIGHT_VISION_EX_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_POISON));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.POISON_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.POISON_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.POISON_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.POISON_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.POISON_5));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOW_BERRIES));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.GLOWING_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.GLOWING_1));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.GLOWING_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_REGENERATION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_3_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_4_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_5));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_5));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.REGENERATION_5_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LONG_SLOW_FALLING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SLOW_FALLING_EX_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SLOW_FALLING_EX_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SLOW_FALLING_EX_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SLOW_FALLING_EX_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SLOW_FALLING_EX_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Blocks.BLUE_ORCHID));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.THICK));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_1));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_1_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_1_EX_1));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_1_EX_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_1_EX_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_1_EX_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_1));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_2_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_2_EX_1));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_2_EX_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_3_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.HASTE_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_STRENGTH));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.STRENGTH_2_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_STRENGTH));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.STRENGTH_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.STRENGTH_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.STRENGTH_3_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.STRENGTH_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.STRENGTH_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_SWIFTNESS));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SWIFTNESS_2_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_SWIFTNESS));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SWIFTNESS_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SWIFTNESS_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SWIFTNESS_3_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SWIFTNESS_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SWIFTNESS_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SWIFTNESS_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.SWIFTNESS_5));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LONG_WATER_BREATHING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WATER_BREATHING_EX_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WATER_BREATHING_EX_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WATER_BREATHING_EX_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WATER_BREATHING_EX_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WATER_BREATHING_EX_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.WEAKNESS));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WEAKNESS_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WEAKNESS_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WEAKNESS_2_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WEAKNESS_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WEAKNESS_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WEAKNESS_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WEAKNESS_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Blocks.WARPED_FUNGUS));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.NAUSEA));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LONG_WEAKNESS));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.WEAKNESS_EX_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.ELYTRA));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEVITATION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.POTION_OF_FLIGHT));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.FERMENTED_SPIDER_EYE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.SLOW_FALLING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEVITATION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEVITATION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.LEVITATION_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.POTION_OF_FLIGHT));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_1));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_3));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_3));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_4));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Blocks.REDSTONE_BLOCK));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_4));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_5));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Blocks.REDSTONE_BLOCK));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_5));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.FLIGHT_EX_6));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Blocks.SCULK_VEIN));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.BLINDNESS));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.BLINDNESS));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(CommonSenseModPotions.BLINDNESS_EX_1));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		registration.addRecipes(RecipeTypes.BREWING, brewingRecipes);
	}
}