/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.commonsenseneo.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.commonsenseneo.item.*;
import net.mcreator.commonsenseneo.CommonSenseMod;

public class CommonSenseModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(CommonSenseMod.MODID);
	public static final DeferredItem<Item> AMBER;
	public static final DeferredItem<Item> AMBER_ORE;
	public static final DeferredItem<Item> DEEP_SLATE_AMBER_ORE;
	public static final DeferredItem<Item> BLOCK_OF_AMBER;
	public static final DeferredItem<Item> AMBER_ARMOR_HELMET;
	public static final DeferredItem<Item> AMBER_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AMBER_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AMBER_ARMOR_BOOTS;
	public static final DeferredItem<Item> AMBER_PICKAXE;
	public static final DeferredItem<Item> AMBER_SHOVEL;
	public static final DeferredItem<Item> AMBER_AXE;
	public static final DeferredItem<Item> LIGHT_BULB;
	public static final DeferredItem<Item> SAW_BLADE;
	public static final DeferredItem<Item> AMBER_HOE;
	public static final DeferredItem<Item> AMBER_SWORD;
	public static final DeferredItem<Item> END_FRAGMENT;
	public static final DeferredItem<Item> END_FRAGMENT_ORE;
	public static final DeferredItem<Item> RAW_ANCIENT_ORE;
	public static final DeferredItem<Item> ANCIENT_INGOT;
	public static final DeferredItem<Item> BLOCK_OF_ANCIENT_ORE;
	public static final DeferredItem<Item> ANCIENT_ARMOR_HELMET;
	public static final DeferredItem<Item> ANCIENT_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ANCIENT_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ANCIENT_ARMOR_BOOTS;
	public static final DeferredItem<Item> NETHERACK_IRON_ORE;
	public static final DeferredItem<Item> NITER;
	public static final DeferredItem<Item> NITER_ORE;
	public static final DeferredItem<Item> BLOCK_OF_NITER;
	public static final DeferredItem<Item> SULFUR;
	public static final DeferredItem<Item> SULFUR_ORE;
	public static final DeferredItem<Item> BLOCK_OF_SULFUR;
	public static final DeferredItem<Item> STONE_BRICK;
	public static final DeferredItem<Item> ROCK;
	public static final DeferredItem<Item> LAUNCHER;
	public static final DeferredItem<Item> STONE_DOOR;
	public static final DeferredItem<Item> STONE_ARMORTEXUTRE_HELMET;
	public static final DeferredItem<Item> STONE_ARMORTEXUTRE_CHESTPLATE;
	public static final DeferredItem<Item> STONE_ARMORTEXUTRE_LEGGINGS;
	public static final DeferredItem<Item> STONE_ARMORTEXUTRE_BOOTS;
	public static final DeferredItem<Item> CHAIN_RING;
	public static final DeferredItem<Item> PRISMARINE_STICK;
	public static final DeferredItem<Item> SPAWN_CORE;
	public static final DeferredItem<Item> ROTTEN_LEATHER;
	public static final DeferredItem<Item> ENCHANTED_GOLDEN_INGOT;
	public static final DeferredItem<Item> SLIME_STRING;
	public static final DeferredItem<Item> NETHERITE_NUGGET;
	public static final DeferredItem<Item> ANCHIENT_SWORD;
	public static final DeferredItem<Item> ANCHIENT_PICKAXE;
	public static final DeferredItem<Item> ANCHIENT_AXE;
	public static final DeferredItem<Item> ANCHIENT_HOE;
	public static final DeferredItem<Item> ANCHIENT_SHOVEL;
	public static final DeferredItem<Item> QUICK_STEP;
	public static final DeferredItem<Item> WOOD_BATTLE_AXE;
	public static final DeferredItem<Item> STONE_BATTLE_AXE;
	public static final DeferredItem<Item> IRON_BATTLE_AXE;
	public static final DeferredItem<Item> GOLD_BATTLE_AXE;
	public static final DeferredItem<Item> DIAMOND_BATTLE_AXE;
	public static final DeferredItem<Item> NETHERITE_BATTLE_AXE;
	public static final DeferredItem<Item> ANCHIENT_BATTLE_AXE;
	public static final DeferredItem<Item> WOOD_AXE_HEAD;
	public static final DeferredItem<Item> STONE_AXE_HEAD;
	public static final DeferredItem<Item> IRON_AXE_HEAD;
	public static final DeferredItem<Item> GOLD_AXE_HEAD;
	public static final DeferredItem<Item> DIAMOND_AXE_HEAD;
	public static final DeferredItem<Item> NETHERITE_AXE_HEAD;
	public static final DeferredItem<Item> ANCIENT_AXE_HEAD;
	public static final DeferredItem<Item> SOULS;
	public static final DeferredItem<Item> SYTHE;
	public static final DeferredItem<Item> BLANK_SPAWN_EGG;
	public static final DeferredItem<Item> WITHER_BONE;
	public static final DeferredItem<Item> ELYTRA_MIDDLE;
	public static final DeferredItem<Item> ELYTRA_LEFT_TOP_WING;
	public static final DeferredItem<Item> ELYTRA_LEFT_BOTTOM_WING;
	public static final DeferredItem<Item> ELYTRA_RIGHT_TOP_WING;
	public static final DeferredItem<Item> ELYTRA_RIGHT_BOTTOM_WING;
	public static final DeferredItem<Item> COMPRESSED_IRON_BLOCK;
	public static final DeferredItem<Item> COMPRESSED_GOLD_BLOCK;
	public static final DeferredItem<Item> COMPRESSED_DIAMOND_BLOCK;
	public static final DeferredItem<Item> COMPRESSED_EMERALD_BLOCK;
	public static final DeferredItem<Item> COMPRESSED_NETHERITE_BLOCK;
	public static final DeferredItem<Item> COMPRESSED_COBBLE_STONE;
	public static final DeferredItem<Item> DOUBLE_COMPRESSED_COBBLE_STONE;
	public static final DeferredItem<Item> TRIPLE_COMPRESSED_COBBLE_STONE;
	public static final DeferredItem<Item> QUADRUPLE_COMPRESSED_COBBLE_STONE;
	public static final DeferredItem<Item> COMPRESSED_NETHERACK;
	public static final DeferredItem<Item> COMPRESSED_ENDSTONE;
	public static final DeferredItem<Item> COMPRESSED_OBSIDAN;
	public static final DeferredItem<Item> DOUBLE_COMPRESSED_OBSIDAN;
	public static final DeferredItem<Item> TRIPLE_COMPRESSED_OBSIDAN;
	public static final DeferredItem<Item> COMPRESSED_COAL_BLOCK;
	public static final DeferredItem<Item> DOUBLE_COMPRESSED_COAL_BLOCK;
	public static final DeferredItem<Item> INRICHED_COAL_BLOCK;
	public static final DeferredItem<Item> BLANK_DISC;
	public static final DeferredItem<Item> COMPRESSED_TNT;
	public static final DeferredItem<Item> DEEPSLATE_NITER_ORE;
	public static final DeferredItem<Item> DEEP_SLATE_SULFUR_ORE;
	public static final DeferredItem<Item> NETHER_STAR_FRAGMENT;
	public static final DeferredItem<Item> ANDESITE_IRON_ORE;
	public static final DeferredItem<Item> ANDESITE_DIAMOND_ORE;
	public static final DeferredItem<Item> ANDESITE_GOLD_ORE;
	public static final DeferredItem<Item> ANDESITE_LAPIS_ORE;
	public static final DeferredItem<Item> ANDESITE_EMERALD_ORE;
	public static final DeferredItem<Item> ANDESITE_REDSTONE_ORE;
	public static final DeferredItem<Item> ANDESITE_COAL_ORE;
	public static final DeferredItem<Item> ANDESITE_COPPER_ORE;
	public static final DeferredItem<Item> DIORITE_IRON_ORE;
	public static final DeferredItem<Item> DIORITE_COPPER_ORE;
	public static final DeferredItem<Item> DIORITE_GOLD_ORE;
	public static final DeferredItem<Item> DIORITE_DIAMOND_ORE;
	public static final DeferredItem<Item> DIORITE_EMERALD_ORE;
	public static final DeferredItem<Item> DIORITE_LAPIS_ORE;
	public static final DeferredItem<Item> DIORITE_REDSTONE_ORE;
	public static final DeferredItem<Item> DIORITE_COAL_ORE;
	public static final DeferredItem<Item> GRANITE_IRON_ORE;
	public static final DeferredItem<Item> GRANITE_GOLD_ORE;
	public static final DeferredItem<Item> GRANITE_COPPER_ORE;
	public static final DeferredItem<Item> GRANITE_DIAMOND_ORE;
	public static final DeferredItem<Item> GRANITE_EMERALD_ORE;
	public static final DeferredItem<Item> GRANITE_REDSTONE_ORE;
	public static final DeferredItem<Item> GRANITE_COAL_ORE;
	public static final DeferredItem<Item> GRANITE_LAPIS_ORE;
	public static final DeferredItem<Item> COOKED_FLESH;
	public static final DeferredItem<Item> ROTTEN_ARMOR_HELMET;
	public static final DeferredItem<Item> ROTTEN_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ROTTEN_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ROTTEN_ARMOR_BOOTS;
	public static final DeferredItem<Item> SNOW_DIRT;
	public static final DeferredItem<Item> CHAIN_MESH;
	public static final DeferredItem<Item> CHAIN_FENCE;
	public static final DeferredItem<Item> OAK_BARK;
	public static final DeferredItem<Item> ACACIA_BARK;
	public static final DeferredItem<Item> BIRCH_BARK;
	public static final DeferredItem<Item> CHERRY_BARK;
	public static final DeferredItem<Item> CRIMSON_BARK;
	public static final DeferredItem<Item> DARK_OAK_BARK;
	public static final DeferredItem<Item> JUNGLE_BARK;
	public static final DeferredItem<Item> MANGROVE_BARK;
	public static final DeferredItem<Item> SPRUCE_BARK;
	public static final DeferredItem<Item> WARP_BARK;
	public static final DeferredItem<Item> OAK_BARK_BLOCK;
	public static final DeferredItem<Item> CHARED_BARK;
	public static final DeferredItem<Item> BIRCH_BARK_BLOCK;
	public static final DeferredItem<Item> ACACIA_BARK_BLOCK;
	public static final DeferredItem<Item> SPRUCE_BARK_BLOCK;
	public static final DeferredItem<Item> CHERRY_BARK_BLOCK;
	public static final DeferredItem<Item> DARK_OAK_BARK_BLOCK;
	public static final DeferredItem<Item> JUNGLE_BARK_BLOCK;
	public static final DeferredItem<Item> MANGROVE_BARK_BLOCK;
	public static final DeferredItem<Item> HOLLOW_STONE_BRICK;
	public static final DeferredItem<Item> HOLLOW_STONE_BRICK_LADDER;
	public static final DeferredItem<Item> SIEVE;
	public static final DeferredItem<Item> LIGHT_BULB_BLOCK;
	public static final DeferredItem<Item> LIGHT_BULB_BLOCK_ON;
	public static final DeferredItem<Item> STEEL_POWDER;
	public static final DeferredItem<Item> STEEL_INGOT;
	public static final DeferredItem<Item> STEEL_PICKAXE;
	public static final DeferredItem<Item> STEEL_AXE;
	public static final DeferredItem<Item> STEEL_HOE;
	public static final DeferredItem<Item> STEEL_SHOVEL;
	public static final DeferredItem<Item> STEEL_SWORD;
	public static final DeferredItem<Item> STEEL_ARMOR_HELMET;
	public static final DeferredItem<Item> STEEL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> STEEL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> STEEL_ARMOR_BOOTS;
	public static final DeferredItem<Item> OBSIDIAN_SHARD;
	public static final DeferredItem<Item> OBSIDIAN_PICKAXE;
	public static final DeferredItem<Item> OBSIDIAN_SWORD;
	public static final DeferredItem<Item> OBSIDIAN_AXE;
	public static final DeferredItem<Item> OBSIDIAN_HOE;
	public static final DeferredItem<Item> OBSIDIAN_SHOVEL;
	public static final DeferredItem<Item> OBSIDIAN_STAIRS;
	public static final DeferredItem<Item> OBSIDIAN_SLAB;
	public static final DeferredItem<Item> OBSIDIAN_PRESSURE_PLATE;
	public static final DeferredItem<Item> OBSIDIAN_WALL;
	public static final DeferredItem<Item> OBSIDIAN_BUTTON;
	public static final DeferredItem<Item> OBSIDIAN_BRICK;
	public static final DeferredItem<Item> STRENGTH_ICON;
	public static final DeferredItem<Item> IMAGEICON;
	public static final DeferredItem<Item> FIRE_RESISTANCE_ICON;
	public static final DeferredItem<Item> HARMING_ICON;
	public static final DeferredItem<Item> HEALING_ICON;
	public static final DeferredItem<Item> INVISIBILITY_ICON;
	public static final DeferredItem<Item> LEAPING_ICON;
	public static final DeferredItem<Item> NIGHT_VISION_ICON;
	public static final DeferredItem<Item> POISON_ICON;
	public static final DeferredItem<Item> REGENERATION_ICON;
	public static final DeferredItem<Item> SLOWNESS_ICON;
	public static final DeferredItem<Item> SWIFTNESS_ICON;
	public static final DeferredItem<Item> WATER_BREATHING_ICON;
	public static final DeferredItem<Item> WEAKNESS_ICON;
	public static final DeferredItem<Item> SLOW_FALLING_ICON;
	public static final DeferredItem<Item> ABSORPTION_ICON;
	public static final DeferredItem<Item> GOLD_CHOCOLATE_BAR;
	public static final DeferredItem<Item> BAD_LUCK_ICON;
	public static final DeferredItem<Item> BAD_OMEN_ICON;
	public static final DeferredItem<Item> BLINDNESS_ICON;
	public static final DeferredItem<Item> CONDUIT_POWER_ICON;
	public static final DeferredItem<Item> DOLPHINS_GRACE_ICON;
	public static final DeferredItem<Item> GLOWING_ICON;
	public static final DeferredItem<Item> HERO_OF_THE_VILLAGE_ICON;
	public static final DeferredItem<Item> HUNGER_ICON;
	public static final DeferredItem<Item> LEVITATION_ICON;
	public static final DeferredItem<Item> LUCK_ICON;
	public static final DeferredItem<Item> MINING_FATIGUE;
	public static final DeferredItem<Item> NAUSEA_ICON;
	public static final DeferredItem<Item> SATURATION_ICON;
	public static final DeferredItem<Item> WITHER_ICON;
	public static final DeferredItem<Item> DARKNESS_ICON;
	public static final DeferredItem<Item> HASTE_ICON;
	public static final DeferredItem<Item> HEALTH_BOOST_ICON;
	public static final DeferredItem<Item> RESISTANCE_ICON;
	public static final DeferredItem<Item> OBSIDIAN_BRICK_STAIRS;
	public static final DeferredItem<Item> OBSIDIAN_BRICK_SLAB;
	public static final DeferredItem<Item> MARBLE_BLOCK;
	public static final DeferredItem<Item> MARBLE_STAIRS;
	public static final DeferredItem<Item> MARBLE_SLAB;
	public static final DeferredItem<Item> MARBLE_WALL;
	public static final DeferredItem<Item> MARBLE_PRESSURE_PLATE;
	public static final DeferredItem<Item> MARBLE_BUTTON;
	public static final DeferredItem<Item> OAK_LEAVES_WALL;
	public static final DeferredItem<Item> CHERRY_LEAVES_WALL;
	public static final DeferredItem<Item> MANGROVE_LEAVES_WALL;
	public static final DeferredItem<Item> JUNGLE_LEAVES_WALL;
	public static final DeferredItem<Item> BIRCH_LEAVES_WALL;
	public static final DeferredItem<Item> ACACIA_LEAVES_WALL;
	public static final DeferredItem<Item> DARK_OAK_LEAVES_WALL;
	public static final DeferredItem<Item> SPRUCE_LEAVES_WALL;
	public static final DeferredItem<Item> AZALEA_LEAVES_WALL;
	public static final DeferredItem<Item> BURNT_LOG;
	public static final DeferredItem<Item> STRIPPED_BURNT_LOG;
	public static final DeferredItem<Item> OAK_STAIRS;
	public static final DeferredItem<Item> OAK_SLAB;
	public static final DeferredItem<Item> IRON_BARS_GATE;
	public static final DeferredItem<Item> IRON_BARS_GATE_OPEN;
	public static final DeferredItem<Item> SPONGE_STEM;
	public static final DeferredItem<Item> STEEL_BLOCK;
	public static final DeferredItem<Item> GLASS_BALL_OF_WATER;
	public static final DeferredItem<Item> GLASS_BALL;
	public static final DeferredItem<Item> ANCIENT_ORE;
	public static final DeferredItem<Item> SLING_SHOT;
	public static final DeferredItem<Item> ACACIA_WOOD_HELMET;
	public static final DeferredItem<Item> ACACIA_WOOD_CHESTPLATE;
	public static final DeferredItem<Item> ACACIA_WOOD_LEGGINGS;
	public static final DeferredItem<Item> ACACIA_WOOD_BOOTS;
	public static final DeferredItem<Item> BIRCH_WOOD_HELMET;
	public static final DeferredItem<Item> BIRCH_WOOD_CHESTPLATE;
	public static final DeferredItem<Item> BIRCH_WOOD_LEGGINGS;
	public static final DeferredItem<Item> BIRCH_WOOD_BOOTS;
	public static final DeferredItem<Item> CHERRY_WOOD_HELMET;
	public static final DeferredItem<Item> CHERRY_WOOD_CHESTPLATE;
	public static final DeferredItem<Item> CHERRY_WOOD_LEGGINGS;
	public static final DeferredItem<Item> CHERRY_WOOD_BOOTS;
	public static final DeferredItem<Item> DARKOAK_WOOD_HELMET;
	public static final DeferredItem<Item> DARKOAK_WOOD_CHESTPLATE;
	public static final DeferredItem<Item> DARKOAK_WOOD_LEGGINGS;
	public static final DeferredItem<Item> DARKOAK_WOOD_BOOTS;
	public static final DeferredItem<Item> JUNGLE_WOOD_HELMET;
	public static final DeferredItem<Item> JUNGLE_WOOD_CHESTPLATE;
	public static final DeferredItem<Item> JUNGLE_WOOD_LEGGINGS;
	public static final DeferredItem<Item> JUNGLE_WOOD_BOOTS;
	public static final DeferredItem<Item> MANGROVE_WOOD_HELMET;
	public static final DeferredItem<Item> MANGROVE_WOOD_CHESTPLATE;
	public static final DeferredItem<Item> MANGROVE_WOOD_LEGGINGS;
	public static final DeferredItem<Item> MANGROVE_WOOD_BOOTS;
	public static final DeferredItem<Item> OAK_WOOD_HELMET;
	public static final DeferredItem<Item> OAK_WOOD_CHESTPLATE;
	public static final DeferredItem<Item> OAK_WOOD_LEGGINGS;
	public static final DeferredItem<Item> OAK_WOOD_BOOTS;
	public static final DeferredItem<Item> SPRUCE_WOOD_HELMET;
	public static final DeferredItem<Item> SPRUCE_WOOD_CHESTPLATE;
	public static final DeferredItem<Item> SPRUCE_WOOD_LEGGINGS;
	public static final DeferredItem<Item> SPRUCE_WOOD_BOOTS;
	public static final DeferredItem<Item> BLAZE_CHARGER;
	public static final DeferredItem<Item> ENDER_PEARL_ROD;
	public static final DeferredItem<Item> PRISMARINE_SPASH_ROD;
	public static final DeferredItem<Item> CLOVER_LEAF;
	public static final DeferredItem<Item> A_CLUFF_OF_CLOVERS;
	public static final DeferredItem<Item> A_CLUFF_OF_MORE_CLOVERS;
	public static final DeferredItem<Item> A_CLUFF_OF_EVEN_MORE_CLOVERS;
	public static final DeferredItem<Item> A_CLUFF_OF_SO_MUCH_CLOVERS;
	public static final DeferredItem<Item> FOUR_LEAF_CLOVER;
	public static final DeferredItem<Item> THREE_LEAF_CLOVER;
	public static final DeferredItem<Item> CLOVER_IN_A_POT;
	public static final DeferredItem<Item> VERTICAL_CHAIN;
	public static final DeferredItem<Item> IRON_TOWER;
	public static final DeferredItem<Item> IRON_TOWER_TOP;
	public static final DeferredItem<Item> ENDSTONE_NETHERITE_ORE;
	public static final DeferredItem<Item> RAW_NETHERITE;
	public static final DeferredItem<Item> STONE_UPGRADE_TEMPLATE;
	public static final DeferredItem<Item> REINFORCED_UPGRADE;
	public static final DeferredItem<Item> BERYLLIUM_ORE;
	public static final DeferredItem<Item> WHITE_CONCRETE_STAIRS;
	public static final DeferredItem<Item> ORANGE_CONCRETE_STAIR;
	public static final DeferredItem<Item> LIGHT_GRAY_CONCRETE_STAIRS;
	public static final DeferredItem<Item> MAGENTA_CONCRETE_STAIRS;
	public static final DeferredItem<Item> LIGHT_BLUE_CONCRETE_STAIRS;
	public static final DeferredItem<Item> YELLOW_CONCRETE_STAIRS;
	public static final DeferredItem<Item> LIME_CONCRETE_STAIRS;
	public static final DeferredItem<Item> PINK_CONCRETE_STAIRS;
	public static final DeferredItem<Item> GRAY_CONCRETE_STAIRS;
	public static final DeferredItem<Item> CYAN_CONCRETE_STAIRS;
	public static final DeferredItem<Item> PURPLE_CONCRETE_STAIRS;
	public static final DeferredItem<Item> BLUE_CONCRETE_STAIRS;
	public static final DeferredItem<Item> BROWN_CONCRETE_STAIRS;
	public static final DeferredItem<Item> GREEN_CONCRETE_STAIRS;
	public static final DeferredItem<Item> RED_CONCRETE_STAIRS;
	public static final DeferredItem<Item> BLACK_CONCRETE_STAIRS;
	public static final DeferredItem<Item> PIG_HIDE;
	public static final DeferredItem<Item> IRON_ORE_CHUNK;
	public static final DeferredItem<Item> STONE_HAMMER;
	public static final DeferredItem<Item> IRON_ORE_DUST;
	public static final DeferredItem<Item> IRON_DUST;
	public static final DeferredItem<Item> IRON_CLUMP;
	public static final DeferredItem<Item> REFINED_IRON_CLUMP;
	public static final DeferredItem<Item> IRON_CLUMP_INGOT;
	public static final DeferredItem<Item> IRON_TOWER_POWERED;
	public static final DeferredItem<Item> IRON_TOWER_TOP_POWERED;
	public static final DeferredItem<Item> RUBY;
	public static final DeferredItem<Item> RUBY_ORE;
	public static final DeferredItem<Item> RUBY_BLOCK;
	public static final DeferredItem<Item> RUBY_PICKAXE;
	public static final DeferredItem<Item> RUBY_SHOVEL;
	public static final DeferredItem<Item> RUBY_HOE;
	public static final DeferredItem<Item> RUBY_AXE;
	public static final DeferredItem<Item> RUBY_SWORD;
	public static final DeferredItem<Item> PALE_OAK_BARK;
	public static final DeferredItem<Item> FLINT_PICKAXE;
	public static final DeferredItem<Item> FLINT_AXE;
	public static final DeferredItem<Item> FLINT_SHOVEL;
	public static final DeferredItem<Item> FLINTHOE;
	public static final DeferredItem<Item> FLINT_SWORD;
	public static final DeferredItem<Item> OLD_STONECUTTER;
	public static final DeferredItem<Item> WHITE_CONCRETE_SLAB;
	public static final DeferredItem<Item> ORANGE_CONCRETE_SLAB;
	public static final DeferredItem<Item> LIGHT_GRAY_CONCRETE_SLAB;
	public static final DeferredItem<Item> GRAY_CONCRETE_SLAB;
	public static final DeferredItem<Item> BLACK_CONCRETE_SLAB;
	public static final DeferredItem<Item> MAGENTA_CONCRETE_SLAB;
	public static final DeferredItem<Item> LIGHT_BLUE_CONCRETE_SLAB;
	public static final DeferredItem<Item> YELLOW_CONCRETE_SLAB;
	public static final DeferredItem<Item> LIME_CONCRETE_SLAB;
	public static final DeferredItem<Item> PINK_CONCRETE_SLAB;
	public static final DeferredItem<Item> CYAN_CONCRETE_SLAB;
	public static final DeferredItem<Item> PURPLE_CONCRETE_SLAB;
	public static final DeferredItem<Item> BLUE_CONCRETE_SLAB;
	public static final DeferredItem<Item> BROWN_CONCRETE_SLAB;
	public static final DeferredItem<Item> GREEN_CONCRETE_SLAB;
	public static final DeferredItem<Item> RED_CONCRETE_SLAB;
	public static final DeferredItem<Item> GLASS_FRAME;
	public static final DeferredItem<Item> FECES;
	public static final DeferredItem<Item> FERTILIZER;
	public static final DeferredItem<Item> BLOCK_OF_FERTILIZER;
	public static final DeferredItem<Item> FLINT_SHEARS;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_14;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_13;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_12;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_11;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_10;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_9;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_8;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_7;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_6;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_5;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_4;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_3;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_2;
	public static final DeferredItem<Item> DIRT_PATH_LAYER_1;
	public static final DeferredItem<Item> DIRT_BALL;
	public static final DeferredItem<Item> THROWABLE_DIRT_BALL;
	static {
		AMBER = REGISTRY.register("amber", AmberItem::new);
		AMBER_ORE = block(CommonSenseModBlocks.AMBER_ORE);
		DEEP_SLATE_AMBER_ORE = block(CommonSenseModBlocks.DEEP_SLATE_AMBER_ORE);
		BLOCK_OF_AMBER = block(CommonSenseModBlocks.BLOCK_OF_AMBER);
		AMBER_ARMOR_HELMET = REGISTRY.register("amber_armor_helmet", AmberArmorItem.Helmet::new);
		AMBER_ARMOR_CHESTPLATE = REGISTRY.register("amber_armor_chestplate", AmberArmorItem.Chestplate::new);
		AMBER_ARMOR_LEGGINGS = REGISTRY.register("amber_armor_leggings", AmberArmorItem.Leggings::new);
		AMBER_ARMOR_BOOTS = REGISTRY.register("amber_armor_boots", AmberArmorItem.Boots::new);
		AMBER_PICKAXE = REGISTRY.register("amber_pickaxe", AmberPickaxeItem::new);
		AMBER_SHOVEL = REGISTRY.register("amber_shovel", AmberShovelItem::new);
		AMBER_AXE = REGISTRY.register("amber_axe", AmberAxeItem::new);
		LIGHT_BULB = REGISTRY.register("light_bulb", LightBulbItem::new);
		SAW_BLADE = REGISTRY.register("saw_blade", SawBladeItem::new);
		AMBER_HOE = REGISTRY.register("amber_hoe", AmberHoeItem::new);
		AMBER_SWORD = REGISTRY.register("amber_sword", AmberSwordItem::new);
		END_FRAGMENT = REGISTRY.register("end_fragment", EndFragmentItem::new);
		END_FRAGMENT_ORE = block(CommonSenseModBlocks.END_FRAGMENT_ORE);
		RAW_ANCIENT_ORE = REGISTRY.register("raw_ancient_ore", RawAncientOreItem::new);
		ANCIENT_INGOT = REGISTRY.register("ancient_ingot", AncientIngotItem::new);
		BLOCK_OF_ANCIENT_ORE = block(CommonSenseModBlocks.BLOCK_OF_ANCIENT_ORE);
		ANCIENT_ARMOR_HELMET = REGISTRY.register("ancient_armor_helmet", AncientArmorItem.Helmet::new);
		ANCIENT_ARMOR_CHESTPLATE = REGISTRY.register("ancient_armor_chestplate", AncientArmorItem.Chestplate::new);
		ANCIENT_ARMOR_LEGGINGS = REGISTRY.register("ancient_armor_leggings", AncientArmorItem.Leggings::new);
		ANCIENT_ARMOR_BOOTS = REGISTRY.register("ancient_armor_boots", AncientArmorItem.Boots::new);
		NETHERACK_IRON_ORE = block(CommonSenseModBlocks.NETHERACK_IRON_ORE);
		NITER = REGISTRY.register("niter", NiterItem::new);
		NITER_ORE = block(CommonSenseModBlocks.NITER_ORE);
		BLOCK_OF_NITER = block(CommonSenseModBlocks.BLOCK_OF_NITER);
		SULFUR = REGISTRY.register("sulfur", SulfurItem::new);
		SULFUR_ORE = block(CommonSenseModBlocks.SULFUR_ORE);
		BLOCK_OF_SULFUR = block(CommonSenseModBlocks.BLOCK_OF_SULFUR);
		STONE_BRICK = REGISTRY.register("stone_brick", StoneBrickItem::new);
		ROCK = REGISTRY.register("rock", RockItem::new);
		LAUNCHER = REGISTRY.register("launcher", LauncherItem::new);
		STONE_DOOR = doubleBlock(CommonSenseModBlocks.STONE_DOOR);
		STONE_ARMORTEXUTRE_HELMET = REGISTRY.register("stone_armortexutre_helmet", StoneArmortexutreItem.Helmet::new);
		STONE_ARMORTEXUTRE_CHESTPLATE = REGISTRY.register("stone_armortexutre_chestplate", StoneArmortexutreItem.Chestplate::new);
		STONE_ARMORTEXUTRE_LEGGINGS = REGISTRY.register("stone_armortexutre_leggings", StoneArmortexutreItem.Leggings::new);
		STONE_ARMORTEXUTRE_BOOTS = REGISTRY.register("stone_armortexutre_boots", StoneArmortexutreItem.Boots::new);
		CHAIN_RING = REGISTRY.register("chain_ring", ChainRingItem::new);
		PRISMARINE_STICK = REGISTRY.register("prismarine_stick", PrismarineStickItem::new);
		SPAWN_CORE = REGISTRY.register("spawn_core", SpawnCoreItem::new);
		ROTTEN_LEATHER = REGISTRY.register("rotten_leather", RottenLeatherItem::new);
		ENCHANTED_GOLDEN_INGOT = REGISTRY.register("enchanted_golden_ingot", EnchantedGoldenIngotItem::new);
		SLIME_STRING = REGISTRY.register("slime_string", SlimeStringItem::new);
		NETHERITE_NUGGET = REGISTRY.register("netherite_nugget", NetheriteNuggetItem::new);
		ANCHIENT_SWORD = REGISTRY.register("anchient_sword", AnchientSwordItem::new);
		ANCHIENT_PICKAXE = REGISTRY.register("anchient_pickaxe", AnchientPickaxeItem::new);
		ANCHIENT_AXE = REGISTRY.register("anchient_axe", AnchientAxeItem::new);
		ANCHIENT_HOE = REGISTRY.register("anchient_hoe", AnchientHoeItem::new);
		ANCHIENT_SHOVEL = REGISTRY.register("anchient_shovel", AnchientShovelItem::new);
		QUICK_STEP = block(CommonSenseModBlocks.QUICK_STEP);
		WOOD_BATTLE_AXE = REGISTRY.register("wood_battle_axe", WoodBattleAxeItem::new);
		STONE_BATTLE_AXE = REGISTRY.register("stone_battle_axe", StoneBattleAxeItem::new);
		IRON_BATTLE_AXE = REGISTRY.register("iron_battle_axe", IronBattleAxeItem::new);
		GOLD_BATTLE_AXE = REGISTRY.register("gold_battle_axe", GoldBattleAxeItem::new);
		DIAMOND_BATTLE_AXE = REGISTRY.register("diamond_battle_axe", DiamondBattleAxeItem::new);
		NETHERITE_BATTLE_AXE = REGISTRY.register("netherite_battle_axe", NetheriteBattleAxeItem::new);
		ANCHIENT_BATTLE_AXE = REGISTRY.register("anchient_battle_axe", AnchientBattleAxeItem::new);
		WOOD_AXE_HEAD = REGISTRY.register("wood_axe_head", WoodAxeHeadItem::new);
		STONE_AXE_HEAD = REGISTRY.register("stone_axe_head", StoneAxeHeadItem::new);
		IRON_AXE_HEAD = REGISTRY.register("iron_axe_head", IronAxeHeadItem::new);
		GOLD_AXE_HEAD = REGISTRY.register("gold_axe_head", GoldAxeHeadItem::new);
		DIAMOND_AXE_HEAD = REGISTRY.register("diamond_axe_head", DiamondAxeHeadItem::new);
		NETHERITE_AXE_HEAD = REGISTRY.register("netherite_axe_head", NetheriteAxeHeadItem::new);
		ANCIENT_AXE_HEAD = REGISTRY.register("ancient_axe_head", AncientAxeHeadItem::new);
		SOULS = REGISTRY.register("souls", SoulsItem::new);
		SYTHE = REGISTRY.register("sythe", SytheItem::new);
		BLANK_SPAWN_EGG = REGISTRY.register("blank_spawn_egg", BlankSpawnEggItem::new);
		WITHER_BONE = REGISTRY.register("wither_bone", WitherBoneItem::new);
		ELYTRA_MIDDLE = REGISTRY.register("elytra_middle", ElytraMiddleItem::new);
		ELYTRA_LEFT_TOP_WING = REGISTRY.register("elytra_left_top_wing", ElytraLeftTopWingItem::new);
		ELYTRA_LEFT_BOTTOM_WING = REGISTRY.register("elytra_left_bottom_wing", ElytraLeftBottomWingItem::new);
		ELYTRA_RIGHT_TOP_WING = REGISTRY.register("elytra_right_top_wing", ElytraRightTopWingItem::new);
		ELYTRA_RIGHT_BOTTOM_WING = REGISTRY.register("elytra_right_bottom_wing", ElytraRightBottomWingItem::new);
		COMPRESSED_IRON_BLOCK = block(CommonSenseModBlocks.COMPRESSED_IRON_BLOCK);
		COMPRESSED_GOLD_BLOCK = block(CommonSenseModBlocks.COMPRESSED_GOLD_BLOCK);
		COMPRESSED_DIAMOND_BLOCK = block(CommonSenseModBlocks.COMPRESSED_DIAMOND_BLOCK);
		COMPRESSED_EMERALD_BLOCK = block(CommonSenseModBlocks.COMPRESSED_EMERALD_BLOCK);
		COMPRESSED_NETHERITE_BLOCK = block(CommonSenseModBlocks.COMPRESSED_NETHERITE_BLOCK);
		COMPRESSED_COBBLE_STONE = block(CommonSenseModBlocks.COMPRESSED_COBBLE_STONE);
		DOUBLE_COMPRESSED_COBBLE_STONE = block(CommonSenseModBlocks.DOUBLE_COMPRESSED_COBBLE_STONE);
		TRIPLE_COMPRESSED_COBBLE_STONE = block(CommonSenseModBlocks.TRIPLE_COMPRESSED_COBBLE_STONE);
		QUADRUPLE_COMPRESSED_COBBLE_STONE = block(CommonSenseModBlocks.QUADRUPLE_COMPRESSED_COBBLE_STONE);
		COMPRESSED_NETHERACK = block(CommonSenseModBlocks.COMPRESSED_NETHERACK);
		COMPRESSED_ENDSTONE = block(CommonSenseModBlocks.COMPRESSED_ENDSTONE);
		COMPRESSED_OBSIDAN = block(CommonSenseModBlocks.COMPRESSED_OBSIDAN);
		DOUBLE_COMPRESSED_OBSIDAN = block(CommonSenseModBlocks.DOUBLE_COMPRESSED_OBSIDAN);
		TRIPLE_COMPRESSED_OBSIDAN = block(CommonSenseModBlocks.TRIPLE_COMPRESSED_OBSIDAN);
		COMPRESSED_COAL_BLOCK = block(CommonSenseModBlocks.COMPRESSED_COAL_BLOCK);
		DOUBLE_COMPRESSED_COAL_BLOCK = block(CommonSenseModBlocks.DOUBLE_COMPRESSED_COAL_BLOCK);
		INRICHED_COAL_BLOCK = block(CommonSenseModBlocks.INRICHED_COAL_BLOCK);
		BLANK_DISC = REGISTRY.register("blank_disc", BlankDiscItem::new);
		COMPRESSED_TNT = block(CommonSenseModBlocks.COMPRESSED_TNT);
		DEEPSLATE_NITER_ORE = block(CommonSenseModBlocks.DEEPSLATE_NITER_ORE);
		DEEP_SLATE_SULFUR_ORE = block(CommonSenseModBlocks.DEEP_SLATE_SULFUR_ORE);
		NETHER_STAR_FRAGMENT = REGISTRY.register("nether_star_fragment", NetherStarFragmentItem::new);
		ANDESITE_IRON_ORE = block(CommonSenseModBlocks.ANDESITE_IRON_ORE);
		ANDESITE_DIAMOND_ORE = block(CommonSenseModBlocks.ANDESITE_DIAMOND_ORE);
		ANDESITE_GOLD_ORE = block(CommonSenseModBlocks.ANDESITE_GOLD_ORE);
		ANDESITE_LAPIS_ORE = block(CommonSenseModBlocks.ANDESITE_LAPIS_ORE);
		ANDESITE_EMERALD_ORE = block(CommonSenseModBlocks.ANDESITE_EMERALD_ORE);
		ANDESITE_REDSTONE_ORE = block(CommonSenseModBlocks.ANDESITE_REDSTONE_ORE);
		ANDESITE_COAL_ORE = block(CommonSenseModBlocks.ANDESITE_COAL_ORE);
		ANDESITE_COPPER_ORE = block(CommonSenseModBlocks.ANDESITE_COPPER_ORE);
		DIORITE_IRON_ORE = block(CommonSenseModBlocks.DIORITE_IRON_ORE);
		DIORITE_COPPER_ORE = block(CommonSenseModBlocks.DIORITE_COPPER_ORE);
		DIORITE_GOLD_ORE = block(CommonSenseModBlocks.DIORITE_GOLD_ORE);
		DIORITE_DIAMOND_ORE = block(CommonSenseModBlocks.DIORITE_DIAMOND_ORE);
		DIORITE_EMERALD_ORE = block(CommonSenseModBlocks.DIORITE_EMERALD_ORE);
		DIORITE_LAPIS_ORE = block(CommonSenseModBlocks.DIORITE_LAPIS_ORE);
		DIORITE_REDSTONE_ORE = block(CommonSenseModBlocks.DIORITE_REDSTONE_ORE);
		DIORITE_COAL_ORE = block(CommonSenseModBlocks.DIORITE_COAL_ORE);
		GRANITE_IRON_ORE = block(CommonSenseModBlocks.GRANITE_IRON_ORE);
		GRANITE_GOLD_ORE = block(CommonSenseModBlocks.GRANITE_GOLD_ORE);
		GRANITE_COPPER_ORE = block(CommonSenseModBlocks.GRANITE_COPPER_ORE);
		GRANITE_DIAMOND_ORE = block(CommonSenseModBlocks.GRANITE_DIAMOND_ORE);
		GRANITE_EMERALD_ORE = block(CommonSenseModBlocks.GRANITE_EMERALD_ORE);
		GRANITE_REDSTONE_ORE = block(CommonSenseModBlocks.GRANITE_REDSTONE_ORE);
		GRANITE_COAL_ORE = block(CommonSenseModBlocks.GRANITE_COAL_ORE);
		GRANITE_LAPIS_ORE = block(CommonSenseModBlocks.GRANITE_LAPIS_ORE);
		COOKED_FLESH = REGISTRY.register("cooked_flesh", CookedFleshItem::new);
		ROTTEN_ARMOR_HELMET = REGISTRY.register("rotten_armor_helmet", RottenArmorItem.Helmet::new);
		ROTTEN_ARMOR_CHESTPLATE = REGISTRY.register("rotten_armor_chestplate", RottenArmorItem.Chestplate::new);
		ROTTEN_ARMOR_LEGGINGS = REGISTRY.register("rotten_armor_leggings", RottenArmorItem.Leggings::new);
		ROTTEN_ARMOR_BOOTS = REGISTRY.register("rotten_armor_boots", RottenArmorItem.Boots::new);
		SNOW_DIRT = block(CommonSenseModBlocks.SNOW_DIRT);
		CHAIN_MESH = REGISTRY.register("chain_mesh", ChainMeshItem::new);
		CHAIN_FENCE = block(CommonSenseModBlocks.CHAIN_FENCE);
		OAK_BARK = REGISTRY.register("oak_bark", OakBarkItem::new);
		ACACIA_BARK = REGISTRY.register("acacia_bark", AcaciaBarkItem::new);
		BIRCH_BARK = REGISTRY.register("birch_bark", BirchBarkItem::new);
		CHERRY_BARK = REGISTRY.register("cherry_bark", CherryBarkItem::new);
		CRIMSON_BARK = REGISTRY.register("crimson_bark", CrimsonBarkItem::new);
		DARK_OAK_BARK = REGISTRY.register("dark_oak_bark", DarkOakBarkItem::new);
		JUNGLE_BARK = REGISTRY.register("jungle_bark", JungleBarkItem::new);
		MANGROVE_BARK = REGISTRY.register("mangrove_bark", MangroveBarkItem::new);
		SPRUCE_BARK = REGISTRY.register("spruce_bark", SpruceBarkItem::new);
		WARP_BARK = REGISTRY.register("warp_bark", WarpBarkItem::new);
		OAK_BARK_BLOCK = block(CommonSenseModBlocks.OAK_BARK_BLOCK);
		CHARED_BARK = REGISTRY.register("chared_bark", CharedBarkItem::new);
		BIRCH_BARK_BLOCK = block(CommonSenseModBlocks.BIRCH_BARK_BLOCK);
		ACACIA_BARK_BLOCK = block(CommonSenseModBlocks.ACACIA_BARK_BLOCK);
		SPRUCE_BARK_BLOCK = block(CommonSenseModBlocks.SPRUCE_BARK_BLOCK);
		CHERRY_BARK_BLOCK = block(CommonSenseModBlocks.CHERRY_BARK_BLOCK);
		DARK_OAK_BARK_BLOCK = block(CommonSenseModBlocks.DARK_OAK_BARK_BLOCK);
		JUNGLE_BARK_BLOCK = block(CommonSenseModBlocks.JUNGLE_BARK_BLOCK);
		MANGROVE_BARK_BLOCK = block(CommonSenseModBlocks.MANGROVE_BARK_BLOCK);
		HOLLOW_STONE_BRICK = block(CommonSenseModBlocks.HOLLOW_STONE_BRICK);
		HOLLOW_STONE_BRICK_LADDER = block(CommonSenseModBlocks.HOLLOW_STONE_BRICK_LADDER);
		SIEVE = REGISTRY.register("sieve", SieveItem::new);
		LIGHT_BULB_BLOCK = block(CommonSenseModBlocks.LIGHT_BULB_BLOCK);
		LIGHT_BULB_BLOCK_ON = block(CommonSenseModBlocks.LIGHT_BULB_BLOCK_ON);
		STEEL_POWDER = REGISTRY.register("steel_powder", SteelPowderItem::new);
		STEEL_INGOT = REGISTRY.register("steel_ingot", SteelIngotItem::new);
		STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", SteelPickaxeItem::new);
		STEEL_AXE = REGISTRY.register("steel_axe", SteelAxeItem::new);
		STEEL_HOE = REGISTRY.register("steel_hoe", SteelHoeItem::new);
		STEEL_SHOVEL = REGISTRY.register("steel_shovel", SteelShovelItem::new);
		STEEL_SWORD = REGISTRY.register("steel_sword", SteelSwordItem::new);
		STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", SteelArmorItem.Helmet::new);
		STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", SteelArmorItem.Chestplate::new);
		STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", SteelArmorItem.Leggings::new);
		STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", SteelArmorItem.Boots::new);
		OBSIDIAN_SHARD = REGISTRY.register("obsidian_shard", ObsidianShardItem::new);
		OBSIDIAN_PICKAXE = REGISTRY.register("obsidian_pickaxe", ObsidianPickaxeItem::new);
		OBSIDIAN_SWORD = REGISTRY.register("obsidian_sword", ObsidianSwordItem::new);
		OBSIDIAN_AXE = REGISTRY.register("obsidian_axe", ObsidianAxeItem::new);
		OBSIDIAN_HOE = REGISTRY.register("obsidian_hoe", ObsidianHoeItem::new);
		OBSIDIAN_SHOVEL = REGISTRY.register("obsidian_shovel", ObsidianShovelItem::new);
		OBSIDIAN_STAIRS = block(CommonSenseModBlocks.OBSIDIAN_STAIRS);
		OBSIDIAN_SLAB = block(CommonSenseModBlocks.OBSIDIAN_SLAB);
		OBSIDIAN_PRESSURE_PLATE = block(CommonSenseModBlocks.OBSIDIAN_PRESSURE_PLATE);
		OBSIDIAN_WALL = block(CommonSenseModBlocks.OBSIDIAN_WALL);
		OBSIDIAN_BUTTON = block(CommonSenseModBlocks.OBSIDIAN_BUTTON);
		OBSIDIAN_BRICK = block(CommonSenseModBlocks.OBSIDIAN_BRICK);
		STRENGTH_ICON = REGISTRY.register("strength_icon", StrengthIconItem::new);
		IMAGEICON = REGISTRY.register("imageicon", ImageiconItem::new);
		FIRE_RESISTANCE_ICON = REGISTRY.register("fire_resistance_icon", FireResistanceIconItem::new);
		HARMING_ICON = REGISTRY.register("harming_icon", HarmingIconItem::new);
		HEALING_ICON = REGISTRY.register("healing_icon", HealingIconItem::new);
		INVISIBILITY_ICON = REGISTRY.register("invisibility_icon", InvisibilityIconItem::new);
		LEAPING_ICON = REGISTRY.register("leaping_icon", LeapingIconItem::new);
		NIGHT_VISION_ICON = REGISTRY.register("night_vision_icon", NightVisionIconItem::new);
		POISON_ICON = REGISTRY.register("poison_icon", PoisonIconItem::new);
		REGENERATION_ICON = REGISTRY.register("regeneration_icon", RegenerationIconItem::new);
		SLOWNESS_ICON = REGISTRY.register("slowness_icon", SlownessIconItem::new);
		SWIFTNESS_ICON = REGISTRY.register("swiftness_icon", SwiftnessIconItem::new);
		WATER_BREATHING_ICON = REGISTRY.register("water_breathing_icon", WaterBreathingIconItem::new);
		WEAKNESS_ICON = REGISTRY.register("weakness_icon", WeaknessIconItem::new);
		SLOW_FALLING_ICON = REGISTRY.register("slow_falling_icon", SlowFallingIconItem::new);
		ABSORPTION_ICON = REGISTRY.register("absorption_icon", AbsorptionIconItem::new);
		GOLD_CHOCOLATE_BAR = REGISTRY.register("gold_chocolate_bar", GoldChocolateBarItem::new);
		BAD_LUCK_ICON = REGISTRY.register("bad_luck_icon", BadLuckIconItem::new);
		BAD_OMEN_ICON = REGISTRY.register("bad_omen_icon", BadOmenIconItem::new);
		BLINDNESS_ICON = REGISTRY.register("blindness_icon", BlindnessIconItem::new);
		CONDUIT_POWER_ICON = REGISTRY.register("conduit_power_icon", ConduitPowerIconItem::new);
		DOLPHINS_GRACE_ICON = REGISTRY.register("dolphins_grace_icon", DolphinsGraceIconItem::new);
		GLOWING_ICON = REGISTRY.register("glowing_icon", GlowingIconItem::new);
		HERO_OF_THE_VILLAGE_ICON = REGISTRY.register("hero_of_the_village_icon", HeroOfTheVillageIconItem::new);
		HUNGER_ICON = REGISTRY.register("hunger_icon", HungerIconItem::new);
		LEVITATION_ICON = REGISTRY.register("levitation_icon", LevitationIconItem::new);
		LUCK_ICON = REGISTRY.register("luck_icon", LuckIconItem::new);
		MINING_FATIGUE = REGISTRY.register("mining_fatigue", MiningFatigueItem::new);
		NAUSEA_ICON = REGISTRY.register("nausea_icon", NauseaIconItem::new);
		SATURATION_ICON = REGISTRY.register("saturation_icon", SaturationIconItem::new);
		WITHER_ICON = REGISTRY.register("wither_icon", WitherIconItem::new);
		DARKNESS_ICON = REGISTRY.register("darkness_icon", DarknessIconItem::new);
		HASTE_ICON = REGISTRY.register("haste_icon", HasteIconItem::new);
		HEALTH_BOOST_ICON = REGISTRY.register("health_boost_icon", HealthBoostIconItem::new);
		RESISTANCE_ICON = REGISTRY.register("resistance_icon", ResistanceIconItem::new);
		OBSIDIAN_BRICK_STAIRS = block(CommonSenseModBlocks.OBSIDIAN_BRICK_STAIRS);
		OBSIDIAN_BRICK_SLAB = block(CommonSenseModBlocks.OBSIDIAN_BRICK_SLAB);
		MARBLE_BLOCK = block(CommonSenseModBlocks.MARBLE_BLOCK);
		MARBLE_STAIRS = block(CommonSenseModBlocks.MARBLE_STAIRS);
		MARBLE_SLAB = block(CommonSenseModBlocks.MARBLE_SLAB);
		MARBLE_WALL = block(CommonSenseModBlocks.MARBLE_WALL);
		MARBLE_PRESSURE_PLATE = block(CommonSenseModBlocks.MARBLE_PRESSURE_PLATE);
		MARBLE_BUTTON = block(CommonSenseModBlocks.MARBLE_BUTTON);
		OAK_LEAVES_WALL = block(CommonSenseModBlocks.OAK_LEAVES_WALL);
		CHERRY_LEAVES_WALL = block(CommonSenseModBlocks.CHERRY_LEAVES_WALL);
		MANGROVE_LEAVES_WALL = block(CommonSenseModBlocks.MANGROVE_LEAVES_WALL);
		JUNGLE_LEAVES_WALL = block(CommonSenseModBlocks.JUNGLE_LEAVES_WALL);
		BIRCH_LEAVES_WALL = block(CommonSenseModBlocks.BIRCH_LEAVES_WALL);
		ACACIA_LEAVES_WALL = block(CommonSenseModBlocks.ACACIA_LEAVES_WALL);
		DARK_OAK_LEAVES_WALL = block(CommonSenseModBlocks.DARK_OAK_LEAVES_WALL);
		SPRUCE_LEAVES_WALL = block(CommonSenseModBlocks.SPRUCE_LEAVES_WALL);
		AZALEA_LEAVES_WALL = block(CommonSenseModBlocks.AZALEA_LEAVES_WALL);
		BURNT_LOG = block(CommonSenseModBlocks.BURNT_LOG);
		STRIPPED_BURNT_LOG = block(CommonSenseModBlocks.STRIPPED_BURNT_LOG);
		OAK_STAIRS = block(CommonSenseModBlocks.OAK_STAIRS);
		OAK_SLAB = block(CommonSenseModBlocks.OAK_SLAB);
		IRON_BARS_GATE = block(CommonSenseModBlocks.IRON_BARS_GATE);
		IRON_BARS_GATE_OPEN = block(CommonSenseModBlocks.IRON_BARS_GATE_OPEN);
		SPONGE_STEM = block(CommonSenseModBlocks.SPONGE_STEM);
		STEEL_BLOCK = block(CommonSenseModBlocks.STEEL_BLOCK);
		GLASS_BALL_OF_WATER = REGISTRY.register("glass_ball_of_water", GlassBallOfWaterItem::new);
		GLASS_BALL = REGISTRY.register("glass_ball", GlassBallItem::new);
		ANCIENT_ORE = block(CommonSenseModBlocks.ANCIENT_ORE);
		SLING_SHOT = REGISTRY.register("sling_shot", SlingShotItem::new);
		ACACIA_WOOD_HELMET = REGISTRY.register("acacia_wood_helmet", AcaciaWoodItem.Helmet::new);
		ACACIA_WOOD_CHESTPLATE = REGISTRY.register("acacia_wood_chestplate", AcaciaWoodItem.Chestplate::new);
		ACACIA_WOOD_LEGGINGS = REGISTRY.register("acacia_wood_leggings", AcaciaWoodItem.Leggings::new);
		ACACIA_WOOD_BOOTS = REGISTRY.register("acacia_wood_boots", AcaciaWoodItem.Boots::new);
		BIRCH_WOOD_HELMET = REGISTRY.register("birch_wood_helmet", BirchWoodItem.Helmet::new);
		BIRCH_WOOD_CHESTPLATE = REGISTRY.register("birch_wood_chestplate", BirchWoodItem.Chestplate::new);
		BIRCH_WOOD_LEGGINGS = REGISTRY.register("birch_wood_leggings", BirchWoodItem.Leggings::new);
		BIRCH_WOOD_BOOTS = REGISTRY.register("birch_wood_boots", BirchWoodItem.Boots::new);
		CHERRY_WOOD_HELMET = REGISTRY.register("cherry_wood_helmet", CherryWoodItem.Helmet::new);
		CHERRY_WOOD_CHESTPLATE = REGISTRY.register("cherry_wood_chestplate", CherryWoodItem.Chestplate::new);
		CHERRY_WOOD_LEGGINGS = REGISTRY.register("cherry_wood_leggings", CherryWoodItem.Leggings::new);
		CHERRY_WOOD_BOOTS = REGISTRY.register("cherry_wood_boots", CherryWoodItem.Boots::new);
		DARKOAK_WOOD_HELMET = REGISTRY.register("darkoak_wood_helmet", DarkoakWoodItem.Helmet::new);
		DARKOAK_WOOD_CHESTPLATE = REGISTRY.register("darkoak_wood_chestplate", DarkoakWoodItem.Chestplate::new);
		DARKOAK_WOOD_LEGGINGS = REGISTRY.register("darkoak_wood_leggings", DarkoakWoodItem.Leggings::new);
		DARKOAK_WOOD_BOOTS = REGISTRY.register("darkoak_wood_boots", DarkoakWoodItem.Boots::new);
		JUNGLE_WOOD_HELMET = REGISTRY.register("jungle_wood_helmet", JungleWoodItem.Helmet::new);
		JUNGLE_WOOD_CHESTPLATE = REGISTRY.register("jungle_wood_chestplate", JungleWoodItem.Chestplate::new);
		JUNGLE_WOOD_LEGGINGS = REGISTRY.register("jungle_wood_leggings", JungleWoodItem.Leggings::new);
		JUNGLE_WOOD_BOOTS = REGISTRY.register("jungle_wood_boots", JungleWoodItem.Boots::new);
		MANGROVE_WOOD_HELMET = REGISTRY.register("mangrove_wood_helmet", MangroveWoodItem.Helmet::new);
		MANGROVE_WOOD_CHESTPLATE = REGISTRY.register("mangrove_wood_chestplate", MangroveWoodItem.Chestplate::new);
		MANGROVE_WOOD_LEGGINGS = REGISTRY.register("mangrove_wood_leggings", MangroveWoodItem.Leggings::new);
		MANGROVE_WOOD_BOOTS = REGISTRY.register("mangrove_wood_boots", MangroveWoodItem.Boots::new);
		OAK_WOOD_HELMET = REGISTRY.register("oak_wood_helmet", OakWoodItem.Helmet::new);
		OAK_WOOD_CHESTPLATE = REGISTRY.register("oak_wood_chestplate", OakWoodItem.Chestplate::new);
		OAK_WOOD_LEGGINGS = REGISTRY.register("oak_wood_leggings", OakWoodItem.Leggings::new);
		OAK_WOOD_BOOTS = REGISTRY.register("oak_wood_boots", OakWoodItem.Boots::new);
		SPRUCE_WOOD_HELMET = REGISTRY.register("spruce_wood_helmet", SpruceWoodItem.Helmet::new);
		SPRUCE_WOOD_CHESTPLATE = REGISTRY.register("spruce_wood_chestplate", SpruceWoodItem.Chestplate::new);
		SPRUCE_WOOD_LEGGINGS = REGISTRY.register("spruce_wood_leggings", SpruceWoodItem.Leggings::new);
		SPRUCE_WOOD_BOOTS = REGISTRY.register("spruce_wood_boots", SpruceWoodItem.Boots::new);
		BLAZE_CHARGER = REGISTRY.register("blaze_charger", BlazeChargerItem::new);
		ENDER_PEARL_ROD = REGISTRY.register("ender_pearl_rod", EnderPearlRodItem::new);
		PRISMARINE_SPASH_ROD = REGISTRY.register("prismarine_spash_rod", PrismarineSpashRodItem::new);
		CLOVER_LEAF = REGISTRY.register("clover_leaf", CloverLeafItem::new);
		A_CLUFF_OF_CLOVERS = block(CommonSenseModBlocks.A_CLUFF_OF_CLOVERS);
		A_CLUFF_OF_MORE_CLOVERS = block(CommonSenseModBlocks.A_CLUFF_OF_MORE_CLOVERS);
		A_CLUFF_OF_EVEN_MORE_CLOVERS = block(CommonSenseModBlocks.A_CLUFF_OF_EVEN_MORE_CLOVERS);
		A_CLUFF_OF_SO_MUCH_CLOVERS = block(CommonSenseModBlocks.A_CLUFF_OF_SO_MUCH_CLOVERS);
		FOUR_LEAF_CLOVER = REGISTRY.register("four_leaf_clover", FourLeafCloverItem::new);
		THREE_LEAF_CLOVER = REGISTRY.register("three_leaf_clover", ThreeLeafCloverItem::new);
		CLOVER_IN_A_POT = block(CommonSenseModBlocks.CLOVER_IN_A_POT);
		VERTICAL_CHAIN = block(CommonSenseModBlocks.VERTICAL_CHAIN);
		IRON_TOWER = block(CommonSenseModBlocks.IRON_TOWER);
		IRON_TOWER_TOP = block(CommonSenseModBlocks.IRON_TOWER_TOP);
		ENDSTONE_NETHERITE_ORE = block(CommonSenseModBlocks.ENDSTONE_NETHERITE_ORE);
		RAW_NETHERITE = REGISTRY.register("raw_netherite", RawNetheriteItem::new);
		STONE_UPGRADE_TEMPLATE = REGISTRY.register("stone_upgrade_template", StoneUpgradeTemplateItem::new);
		REINFORCED_UPGRADE = REGISTRY.register("reinforced_upgrade", ReinforcedUpgradeItem::new);
		BERYLLIUM_ORE = block(CommonSenseModBlocks.BERYLLIUM_ORE);
		WHITE_CONCRETE_STAIRS = block(CommonSenseModBlocks.WHITE_CONCRETE_STAIRS);
		ORANGE_CONCRETE_STAIR = block(CommonSenseModBlocks.ORANGE_CONCRETE_STAIR);
		LIGHT_GRAY_CONCRETE_STAIRS = block(CommonSenseModBlocks.LIGHT_GRAY_CONCRETE_STAIRS);
		MAGENTA_CONCRETE_STAIRS = block(CommonSenseModBlocks.MAGENTA_CONCRETE_STAIRS);
		LIGHT_BLUE_CONCRETE_STAIRS = block(CommonSenseModBlocks.LIGHT_BLUE_CONCRETE_STAIRS);
		YELLOW_CONCRETE_STAIRS = block(CommonSenseModBlocks.YELLOW_CONCRETE_STAIRS);
		LIME_CONCRETE_STAIRS = block(CommonSenseModBlocks.LIME_CONCRETE_STAIRS);
		PINK_CONCRETE_STAIRS = block(CommonSenseModBlocks.PINK_CONCRETE_STAIRS);
		GRAY_CONCRETE_STAIRS = block(CommonSenseModBlocks.GRAY_CONCRETE_STAIRS);
		CYAN_CONCRETE_STAIRS = block(CommonSenseModBlocks.CYAN_CONCRETE_STAIRS);
		PURPLE_CONCRETE_STAIRS = block(CommonSenseModBlocks.PURPLE_CONCRETE_STAIRS);
		BLUE_CONCRETE_STAIRS = block(CommonSenseModBlocks.BLUE_CONCRETE_STAIRS);
		BROWN_CONCRETE_STAIRS = block(CommonSenseModBlocks.BROWN_CONCRETE_STAIRS);
		GREEN_CONCRETE_STAIRS = block(CommonSenseModBlocks.GREEN_CONCRETE_STAIRS);
		RED_CONCRETE_STAIRS = block(CommonSenseModBlocks.RED_CONCRETE_STAIRS);
		BLACK_CONCRETE_STAIRS = block(CommonSenseModBlocks.BLACK_CONCRETE_STAIRS);
		PIG_HIDE = REGISTRY.register("pig_hide", PigHideItem::new);
		IRON_ORE_CHUNK = REGISTRY.register("iron_ore_chunk", IronOreChunkItem::new);
		STONE_HAMMER = REGISTRY.register("stone_hammer", StoneHammerItem::new);
		IRON_ORE_DUST = REGISTRY.register("iron_ore_dust", IronOreDustItem::new);
		IRON_DUST = REGISTRY.register("iron_dust", IronDustItem::new);
		IRON_CLUMP = REGISTRY.register("iron_clump", IronClumpItem::new);
		REFINED_IRON_CLUMP = REGISTRY.register("refined_iron_clump", RefinedIronClumpItem::new);
		IRON_CLUMP_INGOT = REGISTRY.register("iron_clump_ingot", IronClumpIngotItem::new);
		IRON_TOWER_POWERED = block(CommonSenseModBlocks.IRON_TOWER_POWERED);
		IRON_TOWER_TOP_POWERED = block(CommonSenseModBlocks.IRON_TOWER_TOP_POWERED);
		RUBY = REGISTRY.register("ruby", RubyItem::new);
		RUBY_ORE = block(CommonSenseModBlocks.RUBY_ORE);
		RUBY_BLOCK = block(CommonSenseModBlocks.RUBY_BLOCK, new Item.Properties().rarity(Rarity.RARE));
		RUBY_PICKAXE = REGISTRY.register("ruby_pickaxe", RubyPickaxeItem::new);
		RUBY_SHOVEL = REGISTRY.register("ruby_shovel", RubyShovelItem::new);
		RUBY_HOE = REGISTRY.register("ruby_hoe", RubyHoeItem::new);
		RUBY_AXE = REGISTRY.register("ruby_axe", RubyAxeItem::new);
		RUBY_SWORD = REGISTRY.register("ruby_sword", RubySwordItem::new);
		PALE_OAK_BARK = REGISTRY.register("pale_oak_bark", PaleOakBarkItem::new);
		FLINT_PICKAXE = REGISTRY.register("flint_pickaxe", FlintPickaxeItem::new);
		FLINT_AXE = REGISTRY.register("flint_axe", FlintAxeItem::new);
		FLINT_SHOVEL = REGISTRY.register("flint_shovel", FlintShovelItem::new);
		FLINTHOE = REGISTRY.register("flinthoe", FlinthoeItem::new);
		FLINT_SWORD = REGISTRY.register("flint_sword", FlintSwordItem::new);
		OLD_STONECUTTER = block(CommonSenseModBlocks.OLD_STONECUTTER);
		WHITE_CONCRETE_SLAB = block(CommonSenseModBlocks.WHITE_CONCRETE_SLAB);
		ORANGE_CONCRETE_SLAB = block(CommonSenseModBlocks.ORANGE_CONCRETE_SLAB);
		LIGHT_GRAY_CONCRETE_SLAB = block(CommonSenseModBlocks.LIGHT_GRAY_CONCRETE_SLAB);
		GRAY_CONCRETE_SLAB = block(CommonSenseModBlocks.GRAY_CONCRETE_SLAB);
		BLACK_CONCRETE_SLAB = block(CommonSenseModBlocks.BLACK_CONCRETE_SLAB);
		MAGENTA_CONCRETE_SLAB = block(CommonSenseModBlocks.MAGENTA_CONCRETE_SLAB);
		LIGHT_BLUE_CONCRETE_SLAB = block(CommonSenseModBlocks.LIGHT_BLUE_CONCRETE_SLAB);
		YELLOW_CONCRETE_SLAB = block(CommonSenseModBlocks.YELLOW_CONCRETE_SLAB);
		LIME_CONCRETE_SLAB = block(CommonSenseModBlocks.LIME_CONCRETE_SLAB);
		PINK_CONCRETE_SLAB = block(CommonSenseModBlocks.PINK_CONCRETE_SLAB);
		CYAN_CONCRETE_SLAB = block(CommonSenseModBlocks.CYAN_CONCRETE_SLAB);
		PURPLE_CONCRETE_SLAB = block(CommonSenseModBlocks.PURPLE_CONCRETE_SLAB);
		BLUE_CONCRETE_SLAB = block(CommonSenseModBlocks.BLUE_CONCRETE_SLAB);
		BROWN_CONCRETE_SLAB = block(CommonSenseModBlocks.BROWN_CONCRETE_SLAB);
		GREEN_CONCRETE_SLAB = block(CommonSenseModBlocks.GREEN_CONCRETE_SLAB);
		RED_CONCRETE_SLAB = block(CommonSenseModBlocks.RED_CONCRETE_SLAB);
		GLASS_FRAME = block(CommonSenseModBlocks.GLASS_FRAME);
		FECES = REGISTRY.register("feces", FecesItem::new);
		FERTILIZER = REGISTRY.register("fertilizer", FertilizerItem::new);
		BLOCK_OF_FERTILIZER = block(CommonSenseModBlocks.BLOCK_OF_FERTILIZER);
		FLINT_SHEARS = REGISTRY.register("flint_shears", FlintShearsItem::new);
		DIRT_PATH_LAYER_14 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_14);
		DIRT_PATH_LAYER_13 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_13);
		DIRT_PATH_LAYER_12 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_12);
		DIRT_PATH_LAYER_11 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_11);
		DIRT_PATH_LAYER_10 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_10);
		DIRT_PATH_LAYER_9 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_9);
		DIRT_PATH_LAYER_8 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_8);
		DIRT_PATH_LAYER_7 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_7);
		DIRT_PATH_LAYER_6 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_6);
		DIRT_PATH_LAYER_5 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_5);
		DIRT_PATH_LAYER_4 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_4);
		DIRT_PATH_LAYER_3 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_3);
		DIRT_PATH_LAYER_2 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_2);
		DIRT_PATH_LAYER_1 = block(CommonSenseModBlocks.DIRT_PATH_LAYER_1);
		DIRT_BALL = REGISTRY.register("dirt_ball", DirtBallItem::new);
		THROWABLE_DIRT_BALL = REGISTRY.register("throwable_dirt_ball", ThrowableDirtBallItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), properties));
	}
}